var annotated_dup =
[
    [ "API", null, [
      [ "Platform", null, [
        [ "WindowsWindow", "classAPI_1_1Platform_1_1WindowsWindow.html", "classAPI_1_1Platform_1_1WindowsWindow" ]
      ] ],
      [ "RenderingAPI", null, [
        [ "OpenGLVertexBuffer", "classAPI_1_1RenderingAPI_1_1OpenGLVertexBuffer.html", "classAPI_1_1RenderingAPI_1_1OpenGLVertexBuffer" ],
        [ "OpenGLIndexBuffer", "classAPI_1_1RenderingAPI_1_1OpenGLIndexBuffer.html", "classAPI_1_1RenderingAPI_1_1OpenGLIndexBuffer" ],
        [ "OpenGLFramebuffer", "classAPI_1_1RenderingAPI_1_1OpenGLFramebuffer.html", "classAPI_1_1RenderingAPI_1_1OpenGLFramebuffer" ],
        [ "OpenGLRendererAPI", "classAPI_1_1RenderingAPI_1_1OpenGLRendererAPI.html", "classAPI_1_1RenderingAPI_1_1OpenGLRendererAPI" ],
        [ "OpenGLShader", "classAPI_1_1RenderingAPI_1_1OpenGLShader.html", "classAPI_1_1RenderingAPI_1_1OpenGLShader" ],
        [ "OpenGLTexture2D", "classAPI_1_1RenderingAPI_1_1OpenGLTexture2D.html", "classAPI_1_1RenderingAPI_1_1OpenGLTexture2D" ],
        [ "OpenGLUniformBuffer", "classAPI_1_1RenderingAPI_1_1OpenGLUniformBuffer.html", "classAPI_1_1RenderingAPI_1_1OpenGLUniformBuffer" ],
        [ "OpenGLVertexArray", "classAPI_1_1RenderingAPI_1_1OpenGLVertexArray.html", "classAPI_1_1RenderingAPI_1_1OpenGLVertexArray" ]
      ] ]
    ] ],
    [ "Kargono", null, [
      [ "Assets", null, [
        [ "Metadata", "structKargono_1_1Assets_1_1Metadata.html", "structKargono_1_1Assets_1_1Metadata" ],
        [ "TextureMetaData", "structKargono_1_1Assets_1_1TextureMetaData.html", "structKargono_1_1Assets_1_1TextureMetaData" ],
        [ "AudioMetaData", "structKargono_1_1Assets_1_1AudioMetaData.html", "structKargono_1_1Assets_1_1AudioMetaData" ],
        [ "ShaderMetaData", "structKargono_1_1Assets_1_1ShaderMetaData.html", "structKargono_1_1Assets_1_1ShaderMetaData" ],
        [ "FontMetaData", "structKargono_1_1Assets_1_1FontMetaData.html", "structKargono_1_1Assets_1_1FontMetaData" ],
        [ "SceneMetaData", "structKargono_1_1Assets_1_1SceneMetaData.html", null ],
        [ "UIObjectMetaData", "structKargono_1_1Assets_1_1UIObjectMetaData.html", null ],
        [ "InputModeMetaData", "structKargono_1_1Assets_1_1InputModeMetaData.html", null ],
        [ "GameStateMetaData", "structKargono_1_1Assets_1_1GameStateMetaData.html", "structKargono_1_1Assets_1_1GameStateMetaData" ],
        [ "EntityClassMetaData", "structKargono_1_1Assets_1_1EntityClassMetaData.html", "structKargono_1_1Assets_1_1EntityClassMetaData" ],
        [ "ScriptMetaData", "structKargono_1_1Assets_1_1ScriptMetaData.html", "structKargono_1_1Assets_1_1ScriptMetaData" ],
        [ "Asset", "structKargono_1_1Assets_1_1Asset.html", "structKargono_1_1Assets_1_1Asset" ],
        [ "AssetManager", "classKargono_1_1Assets_1_1AssetManager.html", "classKargono_1_1Assets_1_1AssetManager" ]
      ] ],
      [ "Audio", null, [
        [ "AudioSourceSpecification", "structKargono_1_1Audio_1_1AudioSourceSpecification.html", "structKargono_1_1Audio_1_1AudioSourceSpecification" ],
        [ "AudioListenerSpecification", "structKargono_1_1Audio_1_1AudioListenerSpecification.html", "structKargono_1_1Audio_1_1AudioListenerSpecification" ],
        [ "AudioListener", "classKargono_1_1Audio_1_1AudioListener.html", "classKargono_1_1Audio_1_1AudioListener" ],
        [ "AudioBuffer", "classKargono_1_1Audio_1_1AudioBuffer.html", "classKargono_1_1Audio_1_1AudioBuffer" ],
        [ "AudioSource", "classKargono_1_1Audio_1_1AudioSource.html", "classKargono_1_1Audio_1_1AudioSource" ],
        [ "AudioEngine", "classKargono_1_1Audio_1_1AudioEngine.html", "classKargono_1_1Audio_1_1AudioEngine" ]
      ] ],
      [ "EditorUI", null, [
        [ "InlineButtonSpec", "structKargono_1_1EditorUI_1_1InlineButtonSpec.html", "structKargono_1_1EditorUI_1_1InlineButtonSpec" ],
        [ "Editor", "classKargono_1_1EditorUI_1_1Editor.html", null ],
        [ "GenericPopupSpec", "structKargono_1_1EditorUI_1_1GenericPopupSpec.html", "structKargono_1_1EditorUI_1_1GenericPopupSpec" ],
        [ "CheckboxSpec", "structKargono_1_1EditorUI_1_1CheckboxSpec.html", "structKargono_1_1EditorUI_1_1CheckboxSpec" ],
        [ "RadioSelectorSpec", "structKargono_1_1EditorUI_1_1RadioSelectorSpec.html", "structKargono_1_1EditorUI_1_1RadioSelectorSpec" ],
        [ "TextInputSpec", "structKargono_1_1EditorUI_1_1TextInputSpec.html", "structKargono_1_1EditorUI_1_1TextInputSpec" ],
        [ "CollapsingHeaderSpec", "structKargono_1_1EditorUI_1_1CollapsingHeaderSpec.html", "structKargono_1_1EditorUI_1_1CollapsingHeaderSpec" ],
        [ "SelectorHeaderSpec", "structKargono_1_1EditorUI_1_1SelectorHeaderSpec.html", "structKargono_1_1EditorUI_1_1SelectorHeaderSpec" ],
        [ "TableEntry", "structKargono_1_1EditorUI_1_1TableEntry.html", "structKargono_1_1EditorUI_1_1TableEntry" ],
        [ "TableSpec", "structKargono_1_1EditorUI_1_1TableSpec.html", "structKargono_1_1EditorUI_1_1TableSpec" ],
        [ "OptionEntry", "structKargono_1_1EditorUI_1_1OptionEntry.html", "structKargono_1_1EditorUI_1_1OptionEntry" ],
        [ "SelectOptionSpec", "structKargono_1_1EditorUI_1_1SelectOptionSpec.html", "structKargono_1_1EditorUI_1_1SelectOptionSpec" ],
        [ "EditVariableSpec", "structKargono_1_1EditorUI_1_1EditVariableSpec.html", "structKargono_1_1EditorUI_1_1EditVariableSpec" ]
      ] ],
      [ "Events", null, [
        [ "WindowResizeEvent", "classKargono_1_1Events_1_1WindowResizeEvent.html", "classKargono_1_1Events_1_1WindowResizeEvent" ],
        [ "WindowCloseEvent", "classKargono_1_1Events_1_1WindowCloseEvent.html", "classKargono_1_1Events_1_1WindowCloseEvent" ],
        [ "ApplicationCloseEvent", "classKargono_1_1Events_1_1ApplicationCloseEvent.html", "classKargono_1_1Events_1_1ApplicationCloseEvent" ],
        [ "CleanUpTimersEvent", "classKargono_1_1Events_1_1CleanUpTimersEvent.html", "classKargono_1_1Events_1_1CleanUpTimersEvent" ],
        [ "PhysicsCollisionEvent", "classKargono_1_1Events_1_1PhysicsCollisionEvent.html", "classKargono_1_1Events_1_1PhysicsCollisionEvent" ],
        [ "PhysicsCollisionEnd", "classKargono_1_1Events_1_1PhysicsCollisionEnd.html", "classKargono_1_1Events_1_1PhysicsCollisionEnd" ],
        [ "AppTickEvent", "classKargono_1_1Events_1_1AppTickEvent.html", "classKargono_1_1Events_1_1AppTickEvent" ],
        [ "AddTickGeneratorUsage", "classKargono_1_1Events_1_1AddTickGeneratorUsage.html", "classKargono_1_1Events_1_1AddTickGeneratorUsage" ],
        [ "RemoveTickGeneratorUsage", "classKargono_1_1Events_1_1RemoveTickGeneratorUsage.html", "classKargono_1_1Events_1_1RemoveTickGeneratorUsage" ],
        [ "SkipUpdateEvent", "classKargono_1_1Events_1_1SkipUpdateEvent.html", "classKargono_1_1Events_1_1SkipUpdateEvent" ],
        [ "AddExtraUpdateEvent", "classKargono_1_1Events_1_1AddExtraUpdateEvent.html", "classKargono_1_1Events_1_1AddExtraUpdateEvent" ],
        [ "Event", "classKargono_1_1Events_1_1Event.html", "classKargono_1_1Events_1_1Event" ],
        [ "EventDispatcher", "classKargono_1_1Events_1_1EventDispatcher.html", "classKargono_1_1Events_1_1EventDispatcher" ],
        [ "KeyEvent", "classKargono_1_1Events_1_1KeyEvent.html", "classKargono_1_1Events_1_1KeyEvent" ],
        [ "KeyPressedEvent", "classKargono_1_1Events_1_1KeyPressedEvent.html", "classKargono_1_1Events_1_1KeyPressedEvent" ],
        [ "KeyReleasedEvent", "classKargono_1_1Events_1_1KeyReleasedEvent.html", "classKargono_1_1Events_1_1KeyReleasedEvent" ],
        [ "KeyTypedEvent", "classKargono_1_1Events_1_1KeyTypedEvent.html", "classKargono_1_1Events_1_1KeyTypedEvent" ],
        [ "MouseMovedEvent", "classKargono_1_1Events_1_1MouseMovedEvent.html", "classKargono_1_1Events_1_1MouseMovedEvent" ],
        [ "MouseScrolledEvent", "classKargono_1_1Events_1_1MouseScrolledEvent.html", "classKargono_1_1Events_1_1MouseScrolledEvent" ],
        [ "MouseButtonEvent", "classKargono_1_1Events_1_1MouseButtonEvent.html", "classKargono_1_1Events_1_1MouseButtonEvent" ],
        [ "MouseButtonPressedEvent", "classKargono_1_1Events_1_1MouseButtonPressedEvent.html", "classKargono_1_1Events_1_1MouseButtonPressedEvent" ],
        [ "MouseButtonReleasedEvent", "classKargono_1_1Events_1_1MouseButtonReleasedEvent.html", "classKargono_1_1Events_1_1MouseButtonReleasedEvent" ],
        [ "UpdateOnlineUsers", "classKargono_1_1Events_1_1UpdateOnlineUsers.html", "classKargono_1_1Events_1_1UpdateOnlineUsers" ],
        [ "SignalAll", "classKargono_1_1Events_1_1SignalAll.html", "classKargono_1_1Events_1_1SignalAll" ],
        [ "ReceiveSignal", "classKargono_1_1Events_1_1ReceiveSignal.html", "classKargono_1_1Events_1_1ReceiveSignal" ],
        [ "RequestJoinSession", "classKargono_1_1Events_1_1RequestJoinSession.html", "classKargono_1_1Events_1_1RequestJoinSession" ],
        [ "StartSession", "classKargono_1_1Events_1_1StartSession.html", "classKargono_1_1Events_1_1StartSession" ],
        [ "EnableReadyCheck", "classKargono_1_1Events_1_1EnableReadyCheck.html", "classKargono_1_1Events_1_1EnableReadyCheck" ],
        [ "SessionReadyCheck", "classKargono_1_1Events_1_1SessionReadyCheck.html", "classKargono_1_1Events_1_1SessionReadyCheck" ],
        [ "SessionReadyCheckConfirm", "classKargono_1_1Events_1_1SessionReadyCheckConfirm.html", "classKargono_1_1Events_1_1SessionReadyCheckConfirm" ],
        [ "ConnectionTerminated", "classKargono_1_1Events_1_1ConnectionTerminated.html", "classKargono_1_1Events_1_1ConnectionTerminated" ],
        [ "LeaveCurrentSession", "classKargono_1_1Events_1_1LeaveCurrentSession.html", "classKargono_1_1Events_1_1LeaveCurrentSession" ],
        [ "UserLeftSession", "classKargono_1_1Events_1_1UserLeftSession.html", "classKargono_1_1Events_1_1UserLeftSession" ],
        [ "RequestUserCount", "classKargono_1_1Events_1_1RequestUserCount.html", "classKargono_1_1Events_1_1RequestUserCount" ],
        [ "CurrentSessionInit", "classKargono_1_1Events_1_1CurrentSessionInit.html", "classKargono_1_1Events_1_1CurrentSessionInit" ],
        [ "ApproveJoinSession", "classKargono_1_1Events_1_1ApproveJoinSession.html", "classKargono_1_1Events_1_1ApproveJoinSession" ],
        [ "UpdateSessionUserSlot", "classKargono_1_1Events_1_1UpdateSessionUserSlot.html", "classKargono_1_1Events_1_1UpdateSessionUserSlot" ],
        [ "SendAllEntityLocation", "classKargono_1_1Events_1_1SendAllEntityLocation.html", "classKargono_1_1Events_1_1SendAllEntityLocation" ],
        [ "UpdateEntityLocation", "classKargono_1_1Events_1_1UpdateEntityLocation.html", "classKargono_1_1Events_1_1UpdateEntityLocation" ],
        [ "SendAllEntityPhysics", "classKargono_1_1Events_1_1SendAllEntityPhysics.html", "classKargono_1_1Events_1_1SendAllEntityPhysics" ],
        [ "UpdateEntityPhysics", "classKargono_1_1Events_1_1UpdateEntityPhysics.html", "classKargono_1_1Events_1_1UpdateEntityPhysics" ],
        [ "DenyJoinSession", "classKargono_1_1Events_1_1DenyJoinSession.html", "classKargono_1_1Events_1_1DenyJoinSession" ]
      ] ],
      [ "Network", null, [
        [ "Client", "classKargono_1_1Network_1_1Client.html", "classKargono_1_1Network_1_1Client" ],
        [ "ClientInterface", "classKargono_1_1Network_1_1ClientInterface.html", "classKargono_1_1Network_1_1ClientInterface" ],
        [ "Connection", "classKargono_1_1Network_1_1Connection.html", "classKargono_1_1Network_1_1Connection" ],
        [ "ConnectionToClient", "classKargono_1_1Network_1_1ConnectionToClient.html", "classKargono_1_1Network_1_1ConnectionToClient" ],
        [ "ConnectionToServer", "classKargono_1_1Network_1_1ConnectionToServer.html", "classKargono_1_1Network_1_1ConnectionToServer" ],
        [ "tsqueue", "classKargono_1_1Network_1_1tsqueue.html", "classKargono_1_1Network_1_1tsqueue" ],
        [ "MessageHeader", "structKargono_1_1Network_1_1MessageHeader.html", "structKargono_1_1Network_1_1MessageHeader" ],
        [ "Message", "structKargono_1_1Network_1_1Message.html", "structKargono_1_1Network_1_1Message" ],
        [ "owned_message", "structKargono_1_1Network_1_1owned__message.html", "structKargono_1_1Network_1_1owned__message" ],
        [ "LabeledMessage", "structKargono_1_1Network_1_1LabeledMessage.html", "structKargono_1_1Network_1_1LabeledMessage" ],
        [ "Server", "classKargono_1_1Network_1_1Server.html", "classKargono_1_1Network_1_1Server" ],
        [ "ServerInterface", "classKargono_1_1Network_1_1ServerInterface.html", "classKargono_1_1Network_1_1ServerInterface" ],
        [ "SessionInitCache", "structKargono_1_1Network_1_1SessionInitCache.html", "structKargono_1_1Network_1_1SessionInitCache" ],
        [ "Session", "classKargono_1_1Network_1_1Session.html", "classKargono_1_1Network_1_1Session" ],
        [ "UDPClient", "classKargono_1_1Network_1_1UDPClient.html", "classKargono_1_1Network_1_1UDPClient" ],
        [ "UDPServer", "classKargono_1_1Network_1_1UDPServer.html", "classKargono_1_1Network_1_1UDPServer" ],
        [ "UDPService", "classKargono_1_1Network_1_1UDPService.html", "classKargono_1_1Network_1_1UDPService" ]
      ] ],
      [ "Physics", null, [
        [ "ContactListener", "classKargono_1_1Physics_1_1ContactListener.html", "classKargono_1_1Physics_1_1ContactListener" ],
        [ "PhysicsSpecification", "structKargono_1_1Physics_1_1PhysicsSpecification.html", "structKargono_1_1Physics_1_1PhysicsSpecification" ],
        [ "Physics2DWorld", "classKargono_1_1Physics_1_1Physics2DWorld.html", "classKargono_1_1Physics_1_1Physics2DWorld" ]
      ] ],
      [ "Projects", null, [
        [ "ProjectConfig", "structKargono_1_1Projects_1_1ProjectConfig.html", "structKargono_1_1Projects_1_1ProjectConfig" ],
        [ "Project", "classKargono_1_1Projects_1_1Project.html", "classKargono_1_1Projects_1_1Project" ]
      ] ],
      [ "RuntimeUI", null, [
        [ "WidgetCallbacks", "structKargono_1_1RuntimeUI_1_1WidgetCallbacks.html", "structKargono_1_1RuntimeUI_1_1WidgetCallbacks" ],
        [ "UICallbacks", "structKargono_1_1RuntimeUI_1_1UICallbacks.html", "structKargono_1_1RuntimeUI_1_1UICallbacks" ],
        [ "DirectionPointers", "structKargono_1_1RuntimeUI_1_1DirectionPointers.html", "structKargono_1_1RuntimeUI_1_1DirectionPointers" ],
        [ "Widget", "classKargono_1_1RuntimeUI_1_1Widget.html", "classKargono_1_1RuntimeUI_1_1Widget" ],
        [ "TextWidget", "classKargono_1_1RuntimeUI_1_1TextWidget.html", "classKargono_1_1RuntimeUI_1_1TextWidget" ],
        [ "ButtonWidget", "classKargono_1_1RuntimeUI_1_1ButtonWidget.html", "classKargono_1_1RuntimeUI_1_1ButtonWidget" ],
        [ "CheckboxWidget", "classKargono_1_1RuntimeUI_1_1CheckboxWidget.html", "classKargono_1_1RuntimeUI_1_1CheckboxWidget" ],
        [ "ComboWidget", "classKargono_1_1RuntimeUI_1_1ComboWidget.html", "classKargono_1_1RuntimeUI_1_1ComboWidget" ],
        [ "PopupWidget", "classKargono_1_1RuntimeUI_1_1PopupWidget.html", "classKargono_1_1RuntimeUI_1_1PopupWidget" ],
        [ "Window", "structKargono_1_1RuntimeUI_1_1Window.html", "structKargono_1_1RuntimeUI_1_1Window" ],
        [ "UIObject", "structKargono_1_1RuntimeUI_1_1UIObject.html", "structKargono_1_1RuntimeUI_1_1UIObject" ],
        [ "Runtime", "classKargono_1_1RuntimeUI_1_1Runtime.html", "classKargono_1_1RuntimeUI_1_1Runtime" ],
        [ "Text", "classKargono_1_1RuntimeUI_1_1Text.html", null ],
        [ "Character", "structKargono_1_1RuntimeUI_1_1Character.html", "structKargono_1_1RuntimeUI_1_1Character" ],
        [ "Font", "classKargono_1_1RuntimeUI_1_1Font.html", "classKargono_1_1RuntimeUI_1_1Font" ]
      ] ],
      [ "Script", null, [
        [ "ScriptField", "structKargono_1_1Script_1_1ScriptField.html", "structKargono_1_1Script_1_1ScriptField" ],
        [ "ScriptFieldInstance", "structKargono_1_1Script_1_1ScriptFieldInstance.html", "structKargono_1_1Script_1_1ScriptFieldInstance" ],
        [ "ScriptEngine", "classKargono_1_1Script_1_1ScriptEngine.html", "classKargono_1_1Script_1_1ScriptEngine" ],
        [ "ScriptMethod", "structKargono_1_1Script_1_1ScriptMethod.html", "structKargono_1_1Script_1_1ScriptMethod" ],
        [ "ScriptClass", "classKargono_1_1Script_1_1ScriptClass.html", "classKargono_1_1Script_1_1ScriptClass" ],
        [ "ScriptClassCustomCallInstance", "classKargono_1_1Script_1_1ScriptClassCustomCallInstance.html", "classKargono_1_1Script_1_1ScriptClassCustomCallInstance" ],
        [ "ScriptClassEntityInstance", "classKargono_1_1Script_1_1ScriptClassEntityInstance.html", "classKargono_1_1Script_1_1ScriptClassEntityInstance" ],
        [ "ScriptGlue", "classKargono_1_1Script_1_1ScriptGlue.html", null ]
      ] ],
      [ "Scripting", null, [
        [ "ScriptCore", "classKargono_1_1Scripting_1_1ScriptCore.html", null ],
        [ "Script", "classKargono_1_1Scripting_1_1Script.html", "classKargono_1_1Scripting_1_1Script" ],
        [ "ScriptModuleBuilder", "classKargono_1_1Scripting_1_1ScriptModuleBuilder.html", null ]
      ] ],
      [ "Timers", null, [
        [ "ScopedTimer", "classKargono_1_1Timers_1_1ScopedTimer.html", "classKargono_1_1Timers_1_1ScopedTimer" ],
        [ "AsyncBusyTimer", "classKargono_1_1Timers_1_1AsyncBusyTimer.html", "classKargono_1_1Timers_1_1AsyncBusyTimer" ]
      ] ],
      [ "Utility", null, [
        [ "Conversions", "classKargono_1_1Utility_1_1Conversions.html", null ],
        [ "FileDialogs", "classKargono_1_1Utility_1_1FileDialogs.html", null ],
        [ "FileSystem", "classKargono_1_1Utility_1_1FileSystem.html", "classKargono_1_1Utility_1_1FileSystem" ],
        [ "Operations", "classKargono_1_1Utility_1_1Operations.html", null ],
        [ "OSCommands", "classKargono_1_1Utility_1_1OSCommands.html", null ],
        [ "Regex", "classKargono_1_1Utility_1_1Regex.html", null ],
        [ "Time", "classKargono_1_1Utility_1_1Time.html", null ]
      ] ],
      [ "RuntimeApp", "classKargono_1_1RuntimeApp.html", "classKargono_1_1RuntimeApp" ],
      [ "Application", "classKargono_1_1Application.html", "classKargono_1_1Application" ],
      [ "AppTickGenerator", "structKargono_1_1AppTickGenerator.html", "structKargono_1_1AppTickGenerator" ],
      [ "AppTickEngine", "classKargono_1_1AppTickEngine.html", null ],
      [ "Buffer", "structKargono_1_1Buffer.html", "structKargono_1_1Buffer" ],
      [ "ScopedBuffer", "structKargono_1_1ScopedBuffer.html", "structKargono_1_1ScopedBuffer" ],
      [ "CommandLineArgs", "structKargono_1_1CommandLineArgs.html", "structKargono_1_1CommandLineArgs" ],
      [ "AppSpec", "structKargono_1_1AppSpec.html", "structKargono_1_1AppSpec" ],
      [ "EngineCore", "classKargono_1_1EngineCore.html", "classKargono_1_1EngineCore" ],
      [ "Log", "classKargono_1_1Log.html", null ],
      [ "Timestep", "classKargono_1_1Timestep.html", "classKargono_1_1Timestep" ],
      [ "UUID", "classKargono_1_1UUID.html", "classKargono_1_1UUID" ],
      [ "WindowProps", "structKargono_1_1WindowProps.html", "structKargono_1_1WindowProps" ],
      [ "Window", "classKargono_1_1Window.html", "classKargono_1_1Window" ],
      [ "WrappedVariable", "classKargono_1_1WrappedVariable.html", "classKargono_1_1WrappedVariable" ],
      [ "WrappedInteger32", "classKargono_1_1WrappedInteger32.html", "classKargono_1_1WrappedInteger32" ],
      [ "WrappedUInteger16", "classKargono_1_1WrappedUInteger16.html", "classKargono_1_1WrappedUInteger16" ],
      [ "WrappedUInteger32", "classKargono_1_1WrappedUInteger32.html", "classKargono_1_1WrappedUInteger32" ],
      [ "WrappedUInteger64", "classKargono_1_1WrappedUInteger64.html", "classKargono_1_1WrappedUInteger64" ],
      [ "WrappedVector3", "classKargono_1_1WrappedVector3.html", "classKargono_1_1WrappedVector3" ],
      [ "WrappedString", "classKargono_1_1WrappedString.html", "classKargono_1_1WrappedString" ],
      [ "WrappedBool", "classKargono_1_1WrappedBool.html", "classKargono_1_1WrappedBool" ],
      [ "WrappedFloat", "classKargono_1_1WrappedFloat.html", "classKargono_1_1WrappedFloat" ],
      [ "WrappedFunction", "classKargono_1_1WrappedFunction.html", "classKargono_1_1WrappedFunction" ],
      [ "WrappedVoidNone", "classKargono_1_1WrappedVoidNone.html", "classKargono_1_1WrappedVoidNone" ],
      [ "WrappedVoidString", "classKargono_1_1WrappedVoidString.html", "classKargono_1_1WrappedVoidString" ],
      [ "WrappedVoidFloat", "classKargono_1_1WrappedVoidFloat.html", "classKargono_1_1WrappedVoidFloat" ],
      [ "WrappedVoidUInt16", "classKargono_1_1WrappedVoidUInt16.html", "classKargono_1_1WrappedVoidUInt16" ],
      [ "WrappedVoidUInt32", "classKargono_1_1WrappedVoidUInt32.html", "classKargono_1_1WrappedVoidUInt32" ],
      [ "WrappedVoidUInt64", "classKargono_1_1WrappedVoidUInt64.html", "classKargono_1_1WrappedVoidUInt64" ],
      [ "WrappedVoidUInt64Float", "classKargono_1_1WrappedVoidUInt64Float.html", "classKargono_1_1WrappedVoidUInt64Float" ],
      [ "WrappedBoolNone", "classKargono_1_1WrappedBoolNone.html", "classKargono_1_1WrappedBoolNone" ],
      [ "WrappedBoolUInt64", "classKargono_1_1WrappedBoolUInt64.html", "classKargono_1_1WrappedBoolUInt64" ],
      [ "WrappedBoolUInt64UInt64", "classKargono_1_1WrappedBoolUInt64UInt64.html", "classKargono_1_1WrappedBoolUInt64UInt64" ],
      [ "WrappedBoolUInt64UInt16UInt64", "classKargono_1_1WrappedBoolUInt64UInt16UInt64.html", "classKargono_1_1WrappedBoolUInt64UInt16UInt64" ],
      [ "InputMode", "classKargono_1_1InputMode.html", "classKargono_1_1InputMode" ],
      [ "InputPolling", "classKargono_1_1InputPolling.html", null ],
      [ "Camera", "classKargono_1_1Camera.html", "classKargono_1_1Camera" ],
      [ "EditorCamera", "classKargono_1_1EditorCamera.html", "classKargono_1_1EditorCamera" ],
      [ "FramebufferDataSpecification", "structKargono_1_1FramebufferDataSpecification.html", "structKargono_1_1FramebufferDataSpecification" ],
      [ "FramebufferAttachmentSpecification", "structKargono_1_1FramebufferAttachmentSpecification.html", "structKargono_1_1FramebufferAttachmentSpecification" ],
      [ "FramebufferSpecification", "structKargono_1_1FramebufferSpecification.html", "structKargono_1_1FramebufferSpecification" ],
      [ "Framebuffer", "classKargono_1_1Framebuffer.html", "classKargono_1_1Framebuffer" ],
      [ "InputBufferElement", "structKargono_1_1InputBufferElement.html", "structKargono_1_1InputBufferElement" ],
      [ "InputBufferLayout", "classKargono_1_1InputBufferLayout.html", "classKargono_1_1InputBufferLayout" ],
      [ "VertexBuffer", "classKargono_1_1VertexBuffer.html", "classKargono_1_1VertexBuffer" ],
      [ "IndexBuffer", "classKargono_1_1IndexBuffer.html", "classKargono_1_1IndexBuffer" ],
      [ "RenderCommand", "classKargono_1_1RenderCommand.html", null ],
      [ "Renderer", "classKargono_1_1Renderer.html", "classKargono_1_1Renderer" ],
      [ "RendererAPI", "classKargono_1_1RendererAPI.html", "classKargono_1_1RendererAPI" ],
      [ "DrawCallBuffer", "structKargono_1_1DrawCallBuffer.html", "structKargono_1_1DrawCallBuffer" ],
      [ "RendererInputSpec", "structKargono_1_1RendererInputSpec.html", "structKargono_1_1RendererInputSpec" ],
      [ "ShaderSpecification", "structKargono_1_1ShaderSpecification.html", "structKargono_1_1ShaderSpecification" ],
      [ "Shader", "classKargono_1_1Shader.html", "classKargono_1_1Shader" ],
      [ "ShaderBuilder", "classKargono_1_1ShaderBuilder.html", null ],
      [ "Shape", "classKargono_1_1Shape.html", "classKargono_1_1Shape" ],
      [ "TextureSpecification", "structKargono_1_1TextureSpecification.html", "structKargono_1_1TextureSpecification" ],
      [ "Texture", "classKargono_1_1Texture.html", "classKargono_1_1Texture" ],
      [ "Texture2D", "classKargono_1_1Texture2D.html", null ],
      [ "UniformElement", "structKargono_1_1UniformElement.html", "structKargono_1_1UniformElement" ],
      [ "UniformBufferList", "classKargono_1_1UniformBufferList.html", "classKargono_1_1UniformBufferList" ],
      [ "UniformBuffer", "classKargono_1_1UniformBuffer.html", "classKargono_1_1UniformBuffer" ],
      [ "VertexArray", "classKargono_1_1VertexArray.html", "classKargono_1_1VertexArray" ],
      [ "IDComponent", "structKargono_1_1IDComponent.html", "structKargono_1_1IDComponent" ],
      [ "TagComponent", "structKargono_1_1TagComponent.html", "structKargono_1_1TagComponent" ],
      [ "TransformComponent", "structKargono_1_1TransformComponent.html", "structKargono_1_1TransformComponent" ],
      [ "CameraComponent", "structKargono_1_1CameraComponent.html", "structKargono_1_1CameraComponent" ],
      [ "NetworkComponent", "structKargono_1_1NetworkComponent.html", "structKargono_1_1NetworkComponent" ],
      [ "AudioComponent", "structKargono_1_1AudioComponent.html", "structKargono_1_1AudioComponent" ],
      [ "MultiAudioComponent", "structKargono_1_1MultiAudioComponent.html", "structKargono_1_1MultiAudioComponent" ],
      [ "ScriptComponent", "structKargono_1_1ScriptComponent.html", "structKargono_1_1ScriptComponent" ],
      [ "Rigidbody2DComponent", "structKargono_1_1Rigidbody2DComponent.html", "structKargono_1_1Rigidbody2DComponent" ],
      [ "BoxCollider2DComponent", "structKargono_1_1BoxCollider2DComponent.html", "structKargono_1_1BoxCollider2DComponent" ],
      [ "ClassInstanceComponent", "structKargono_1_1ClassInstanceComponent.html", "structKargono_1_1ClassInstanceComponent" ],
      [ "CircleCollider2DComponent", "structKargono_1_1CircleCollider2DComponent.html", "structKargono_1_1CircleCollider2DComponent" ],
      [ "ShapeComponent", "structKargono_1_1ShapeComponent.html", "structKargono_1_1ShapeComponent" ],
      [ "ComponentGroup", "structKargono_1_1ComponentGroup.html", null ],
      [ "Entity", "classKargono_1_1Entity.html", "classKargono_1_1Entity" ],
      [ "EntityScripts", "structKargono_1_1EntityScripts.html", "structKargono_1_1EntityScripts" ],
      [ "ClassField", "structKargono_1_1ClassField.html", "structKargono_1_1ClassField" ],
      [ "EntityClass", "classKargono_1_1EntityClass.html", "classKargono_1_1EntityClass" ],
      [ "GameState", "classKargono_1_1GameState.html", "classKargono_1_1GameState" ],
      [ "Scene", "classKargono_1_1Scene.html", "classKargono_1_1Scene" ],
      [ "SceneCamera", "classKargono_1_1SceneCamera.html", "classKargono_1_1SceneCamera" ],
      [ "ServerApp", "classKargono_1_1ServerApp.html", "classKargono_1_1ServerApp" ],
      [ "EditorApp", "classKargono_1_1EditorApp.html", "classKargono_1_1EditorApp" ],
      [ "ContentBrowserPanel", "classKargono_1_1ContentBrowserPanel.html", "classKargono_1_1ContentBrowserPanel" ],
      [ "EntityClassEditor", "classKargono_1_1EntityClassEditor.html", "classKargono_1_1EntityClassEditor" ],
      [ "GameStatePanel", "classKargono_1_1GameStatePanel.html", "classKargono_1_1GameStatePanel" ],
      [ "InputEditorPanel", "classKargono_1_1InputEditorPanel.html", "classKargono_1_1InputEditorPanel" ],
      [ "ImGuiLog", "structKargono_1_1ImGuiLog.html", "structKargono_1_1ImGuiLog" ],
      [ "LogPanel", "classKargono_1_1LogPanel.html", "classKargono_1_1LogPanel" ],
      [ "ProjectPanel", "classKargono_1_1ProjectPanel.html", "classKargono_1_1ProjectPanel" ],
      [ "SceneHierarchyPanel", "classKargono_1_1SceneHierarchyPanel.html", "classKargono_1_1SceneHierarchyPanel" ],
      [ "ScriptEditorPanel", "classKargono_1_1ScriptEditorPanel.html", "classKargono_1_1ScriptEditorPanel" ],
      [ "StatisticsPanel", "classKargono_1_1StatisticsPanel.html", "classKargono_1_1StatisticsPanel" ],
      [ "TextEditorPanel", "classKargono_1_1TextEditorPanel.html", "classKargono_1_1TextEditorPanel" ],
      [ "UIEditorPanel", "classKargono_1_1UIEditorPanel.html", "classKargono_1_1UIEditorPanel" ],
      [ "ViewportPanel", "classKargono_1_1ViewportPanel.html", "classKargono_1_1ViewportPanel" ]
    ] ],
    [ "std", null, [
      [ "hash< Kargono::UUID >", "structstd_1_1hash_3_01Kargono_1_1UUID_01_4.html", "structstd_1_1hash_3_01Kargono_1_1UUID_01_4" ]
    ] ],
    [ "YAML", null, [
      [ "convert< Kargono::Math::vec2 >", "structYAML_1_1convert_3_01Kargono_1_1Math_1_1vec2_01_4.html", null ],
      [ "convert< Kargono::Math::vec3 >", "structYAML_1_1convert_3_01Kargono_1_1Math_1_1vec3_01_4.html", null ],
      [ "convert< Kargono::Math::vec4 >", "structYAML_1_1convert_3_01Kargono_1_1Math_1_1vec4_01_4.html", null ],
      [ "convert< Kargono::Math::ivec2 >", "structYAML_1_1convert_3_01Kargono_1_1Math_1_1ivec2_01_4.html", null ],
      [ "convert< Kargono::Math::ivec3 >", "structYAML_1_1convert_3_01Kargono_1_1Math_1_1ivec3_01_4.html", null ],
      [ "convert< Kargono::Math::ivec4 >", "structYAML_1_1convert_3_01Kargono_1_1Math_1_1ivec4_01_4.html", null ],
      [ "convert< Kargono::UUID >", "structYAML_1_1convert_3_01Kargono_1_1UUID_01_4.html", null ]
    ] ]
];