var annotated_dup =
[
    [ "Kargono", "namespaceKargono.html", [
      [ "Assets", "namespaceKargono_1_1Assets.html", [
        [ "Metadata", "structKargono_1_1Assets_1_1Metadata.html", "structKargono_1_1Assets_1_1Metadata" ],
        [ "TextureMetaData", "structKargono_1_1Assets_1_1TextureMetaData.html", "structKargono_1_1Assets_1_1TextureMetaData" ],
        [ "AudioMetaData", "structKargono_1_1Assets_1_1AudioMetaData.html", "structKargono_1_1Assets_1_1AudioMetaData" ],
        [ "ShaderMetaData", "structKargono_1_1Assets_1_1ShaderMetaData.html", "structKargono_1_1Assets_1_1ShaderMetaData" ],
        [ "FontMetaData", "structKargono_1_1Assets_1_1FontMetaData.html", "structKargono_1_1Assets_1_1FontMetaData" ],
        [ "SceneMetaData", "structKargono_1_1Assets_1_1SceneMetaData.html", null ],
        [ "UserInterfaceMetaData", "structKargono_1_1Assets_1_1UserInterfaceMetaData.html", null ],
        [ "InputModeMetaData", "structKargono_1_1Assets_1_1InputModeMetaData.html", null ],
        [ "GameStateMetaData", "structKargono_1_1Assets_1_1GameStateMetaData.html", "structKargono_1_1Assets_1_1GameStateMetaData" ],
        [ "EntityClassMetaData", "structKargono_1_1Assets_1_1EntityClassMetaData.html", "structKargono_1_1Assets_1_1EntityClassMetaData" ],
        [ "ScriptMetaData", "structKargono_1_1Assets_1_1ScriptMetaData.html", "structKargono_1_1Assets_1_1ScriptMetaData" ],
        [ "Asset", "structKargono_1_1Assets_1_1Asset.html", "structKargono_1_1Assets_1_1Asset" ],
        [ "AssetManager", "classKargono_1_1Assets_1_1AssetManager.html", "classKargono_1_1Assets_1_1AssetManager" ]
      ] ],
      [ "Audio", "namespaceKargono_1_1Audio.html", [
        [ "AudioSourceSpecification", "structKargono_1_1Audio_1_1AudioSourceSpecification.html", "structKargono_1_1Audio_1_1AudioSourceSpecification" ],
        [ "AudioListenerSpecification", "structKargono_1_1Audio_1_1AudioListenerSpecification.html", "structKargono_1_1Audio_1_1AudioListenerSpecification" ],
        [ "AudioListener", "classKargono_1_1Audio_1_1AudioListener.html", "classKargono_1_1Audio_1_1AudioListener" ],
        [ "AudioBuffer", "classKargono_1_1Audio_1_1AudioBuffer.html", "classKargono_1_1Audio_1_1AudioBuffer" ],
        [ "AudioSource", "classKargono_1_1Audio_1_1AudioSource.html", "classKargono_1_1Audio_1_1AudioSource" ],
        [ "AudioContext", "structKargono_1_1Audio_1_1AudioContext.html", "structKargono_1_1Audio_1_1AudioContext" ],
        [ "AudioService", "classKargono_1_1Audio_1_1AudioService.html", "classKargono_1_1Audio_1_1AudioService" ]
      ] ],
      [ "EditorUI", "namespaceKargono_1_1EditorUI.html", [
        [ "InlineButtonSpec", "structKargono_1_1EditorUI_1_1InlineButtonSpec.html", "structKargono_1_1EditorUI_1_1InlineButtonSpec" ],
        [ "EditorUIService", "classKargono_1_1EditorUI_1_1EditorUIService.html", null ],
        [ "GenericPopupSpec", "structKargono_1_1EditorUI_1_1GenericPopupSpec.html", "structKargono_1_1EditorUI_1_1GenericPopupSpec" ],
        [ "CheckboxSpec", "structKargono_1_1EditorUI_1_1CheckboxSpec.html", "structKargono_1_1EditorUI_1_1CheckboxSpec" ],
        [ "EditFloatSpec", "structKargono_1_1EditorUI_1_1EditFloatSpec.html", "structKargono_1_1EditorUI_1_1EditFloatSpec" ],
        [ "EditVec2Spec", "structKargono_1_1EditorUI_1_1EditVec2Spec.html", "structKargono_1_1EditorUI_1_1EditVec2Spec" ],
        [ "EditVec3Spec", "structKargono_1_1EditorUI_1_1EditVec3Spec.html", "structKargono_1_1EditorUI_1_1EditVec3Spec" ],
        [ "RadioSelectorSpec", "structKargono_1_1EditorUI_1_1RadioSelectorSpec.html", "structKargono_1_1EditorUI_1_1RadioSelectorSpec" ],
        [ "TextInputSpec", "structKargono_1_1EditorUI_1_1TextInputSpec.html", "structKargono_1_1EditorUI_1_1TextInputSpec" ],
        [ "ChooseDirectorySpec", "structKargono_1_1EditorUI_1_1ChooseDirectorySpec.html", "structKargono_1_1EditorUI_1_1ChooseDirectorySpec" ],
        [ "CollapsingHeaderSpec", "structKargono_1_1EditorUI_1_1CollapsingHeaderSpec.html", "structKargono_1_1EditorUI_1_1CollapsingHeaderSpec" ],
        [ "PanelHeaderSpec", "structKargono_1_1EditorUI_1_1PanelHeaderSpec.html", "structKargono_1_1EditorUI_1_1PanelHeaderSpec" ],
        [ "TableEntry", "structKargono_1_1EditorUI_1_1TableEntry.html", "structKargono_1_1EditorUI_1_1TableEntry" ],
        [ "TableSpec", "structKargono_1_1EditorUI_1_1TableSpec.html", "structKargono_1_1EditorUI_1_1TableSpec" ],
        [ "OptionEntry", "structKargono_1_1EditorUI_1_1OptionEntry.html", "structKargono_1_1EditorUI_1_1OptionEntry" ],
        [ "SelectOptionSpec", "structKargono_1_1EditorUI_1_1SelectOptionSpec.html", "structKargono_1_1EditorUI_1_1SelectOptionSpec" ],
        [ "EditVariableSpec", "structKargono_1_1EditorUI_1_1EditVariableSpec.html", "structKargono_1_1EditorUI_1_1EditVariableSpec" ]
      ] ],
      [ "Events", "namespaceKargono_1_1Events.html", [
        [ "WindowResizeEvent", "classKargono_1_1Events_1_1WindowResizeEvent.html", "classKargono_1_1Events_1_1WindowResizeEvent" ],
        [ "WindowCloseEvent", "classKargono_1_1Events_1_1WindowCloseEvent.html", "classKargono_1_1Events_1_1WindowCloseEvent" ],
        [ "ApplicationCloseEvent", "classKargono_1_1Events_1_1ApplicationCloseEvent.html", "classKargono_1_1Events_1_1ApplicationCloseEvent" ],
        [ "CleanUpTimersEvent", "classKargono_1_1Events_1_1CleanUpTimersEvent.html", "classKargono_1_1Events_1_1CleanUpTimersEvent" ],
        [ "PhysicsCollisionEvent", "classKargono_1_1Events_1_1PhysicsCollisionEvent.html", "classKargono_1_1Events_1_1PhysicsCollisionEvent" ],
        [ "PhysicsCollisionEnd", "classKargono_1_1Events_1_1PhysicsCollisionEnd.html", "classKargono_1_1Events_1_1PhysicsCollisionEnd" ],
        [ "AppTickEvent", "classKargono_1_1Events_1_1AppTickEvent.html", "classKargono_1_1Events_1_1AppTickEvent" ],
        [ "AddTickGeneratorUsage", "classKargono_1_1Events_1_1AddTickGeneratorUsage.html", "classKargono_1_1Events_1_1AddTickGeneratorUsage" ],
        [ "RemoveTickGeneratorUsage", "classKargono_1_1Events_1_1RemoveTickGeneratorUsage.html", "classKargono_1_1Events_1_1RemoveTickGeneratorUsage" ],
        [ "SkipUpdateEvent", "classKargono_1_1Events_1_1SkipUpdateEvent.html", "classKargono_1_1Events_1_1SkipUpdateEvent" ],
        [ "AddExtraUpdateEvent", "classKargono_1_1Events_1_1AddExtraUpdateEvent.html", "classKargono_1_1Events_1_1AddExtraUpdateEvent" ],
        [ "Event", "classKargono_1_1Events_1_1Event.html", "classKargono_1_1Events_1_1Event" ],
        [ "EventDispatcher", "classKargono_1_1Events_1_1EventDispatcher.html", "classKargono_1_1Events_1_1EventDispatcher" ],
        [ "KeyEvent", "classKargono_1_1Events_1_1KeyEvent.html", "classKargono_1_1Events_1_1KeyEvent" ],
        [ "KeyPressedEvent", "classKargono_1_1Events_1_1KeyPressedEvent.html", "classKargono_1_1Events_1_1KeyPressedEvent" ],
        [ "KeyReleasedEvent", "classKargono_1_1Events_1_1KeyReleasedEvent.html", "classKargono_1_1Events_1_1KeyReleasedEvent" ],
        [ "KeyTypedEvent", "classKargono_1_1Events_1_1KeyTypedEvent.html", "classKargono_1_1Events_1_1KeyTypedEvent" ],
        [ "MouseMovedEvent", "classKargono_1_1Events_1_1MouseMovedEvent.html", "classKargono_1_1Events_1_1MouseMovedEvent" ],
        [ "MouseScrolledEvent", "classKargono_1_1Events_1_1MouseScrolledEvent.html", "classKargono_1_1Events_1_1MouseScrolledEvent" ],
        [ "MouseButtonEvent", "classKargono_1_1Events_1_1MouseButtonEvent.html", "classKargono_1_1Events_1_1MouseButtonEvent" ],
        [ "MouseButtonPressedEvent", "classKargono_1_1Events_1_1MouseButtonPressedEvent.html", "classKargono_1_1Events_1_1MouseButtonPressedEvent" ],
        [ "MouseButtonReleasedEvent", "classKargono_1_1Events_1_1MouseButtonReleasedEvent.html", "classKargono_1_1Events_1_1MouseButtonReleasedEvent" ],
        [ "UpdateOnlineUsers", "classKargono_1_1Events_1_1UpdateOnlineUsers.html", "classKargono_1_1Events_1_1UpdateOnlineUsers" ],
        [ "SignalAll", "classKargono_1_1Events_1_1SignalAll.html", "classKargono_1_1Events_1_1SignalAll" ],
        [ "ReceiveSignal", "classKargono_1_1Events_1_1ReceiveSignal.html", "classKargono_1_1Events_1_1ReceiveSignal" ],
        [ "RequestJoinSession", "classKargono_1_1Events_1_1RequestJoinSession.html", "classKargono_1_1Events_1_1RequestJoinSession" ],
        [ "StartSession", "classKargono_1_1Events_1_1StartSession.html", "classKargono_1_1Events_1_1StartSession" ],
        [ "EnableReadyCheck", "classKargono_1_1Events_1_1EnableReadyCheck.html", "classKargono_1_1Events_1_1EnableReadyCheck" ],
        [ "SessionReadyCheck", "classKargono_1_1Events_1_1SessionReadyCheck.html", "classKargono_1_1Events_1_1SessionReadyCheck" ],
        [ "SessionReadyCheckConfirm", "classKargono_1_1Events_1_1SessionReadyCheckConfirm.html", "classKargono_1_1Events_1_1SessionReadyCheckConfirm" ],
        [ "ConnectionTerminated", "classKargono_1_1Events_1_1ConnectionTerminated.html", "classKargono_1_1Events_1_1ConnectionTerminated" ],
        [ "LeaveCurrentSession", "classKargono_1_1Events_1_1LeaveCurrentSession.html", "classKargono_1_1Events_1_1LeaveCurrentSession" ],
        [ "UserLeftSession", "classKargono_1_1Events_1_1UserLeftSession.html", "classKargono_1_1Events_1_1UserLeftSession" ],
        [ "RequestUserCount", "classKargono_1_1Events_1_1RequestUserCount.html", "classKargono_1_1Events_1_1RequestUserCount" ],
        [ "CurrentSessionInit", "classKargono_1_1Events_1_1CurrentSessionInit.html", "classKargono_1_1Events_1_1CurrentSessionInit" ],
        [ "ApproveJoinSession", "classKargono_1_1Events_1_1ApproveJoinSession.html", "classKargono_1_1Events_1_1ApproveJoinSession" ],
        [ "UpdateSessionUserSlot", "classKargono_1_1Events_1_1UpdateSessionUserSlot.html", "classKargono_1_1Events_1_1UpdateSessionUserSlot" ],
        [ "SendAllEntityLocation", "classKargono_1_1Events_1_1SendAllEntityLocation.html", "classKargono_1_1Events_1_1SendAllEntityLocation" ],
        [ "UpdateEntityLocation", "classKargono_1_1Events_1_1UpdateEntityLocation.html", "classKargono_1_1Events_1_1UpdateEntityLocation" ],
        [ "SendAllEntityPhysics", "classKargono_1_1Events_1_1SendAllEntityPhysics.html", "classKargono_1_1Events_1_1SendAllEntityPhysics" ],
        [ "UpdateEntityPhysics", "classKargono_1_1Events_1_1UpdateEntityPhysics.html", "classKargono_1_1Events_1_1UpdateEntityPhysics" ],
        [ "DenyJoinSession", "classKargono_1_1Events_1_1DenyJoinSession.html", "classKargono_1_1Events_1_1DenyJoinSession" ]
      ] ],
      [ "Input", "namespaceKargono_1_1Input.html", [
        [ "InputActionBinding", "classKargono_1_1Input_1_1InputActionBinding.html", "classKargono_1_1Input_1_1InputActionBinding" ],
        [ "KeyboardActionBinding", "classKargono_1_1Input_1_1KeyboardActionBinding.html", "classKargono_1_1Input_1_1KeyboardActionBinding" ],
        [ "InputMode", "classKargono_1_1Input_1_1InputMode.html", "classKargono_1_1Input_1_1InputMode" ],
        [ "InputModeService", "classKargono_1_1Input_1_1InputModeService.html", null ],
        [ "InputService", "classKargono_1_1Input_1_1InputService.html", null ]
      ] ],
      [ "Network", "namespaceKargono_1_1Network.html", [
        [ "UDPClientConnection", "classKargono_1_1Network_1_1UDPClientConnection.html", "classKargono_1_1Network_1_1UDPClientConnection" ],
        [ "TCPClientConnection", "classKargono_1_1Network_1_1TCPClientConnection.html", "classKargono_1_1Network_1_1TCPClientConnection" ],
        [ "Client", "classKargono_1_1Network_1_1Client.html", "classKargono_1_1Network_1_1Client" ],
        [ "ClientService", "classKargono_1_1Network_1_1ClientService.html", null ],
        [ "MessageHeader", "structKargono_1_1Network_1_1MessageHeader.html", "structKargono_1_1Network_1_1MessageHeader" ],
        [ "Message", "structKargono_1_1Network_1_1Message.html", "structKargono_1_1Network_1_1Message" ],
        [ "owned_message", "structKargono_1_1Network_1_1owned__message.html", "structKargono_1_1Network_1_1owned__message" ],
        [ "LabeledMessage", "structKargono_1_1Network_1_1LabeledMessage.html", "structKargono_1_1Network_1_1LabeledMessage" ],
        [ "UDPServerConnection", "classKargono_1_1Network_1_1UDPServerConnection.html", "classKargono_1_1Network_1_1UDPServerConnection" ],
        [ "TCPServerConnection", "classKargono_1_1Network_1_1TCPServerConnection.html", "classKargono_1_1Network_1_1TCPServerConnection" ],
        [ "Server", "classKargono_1_1Network_1_1Server.html", "classKargono_1_1Network_1_1Server" ],
        [ "ServerService", "classKargono_1_1Network_1_1ServerService.html", null ],
        [ "SessionInitCache", "structKargono_1_1Network_1_1SessionInitCache.html", "structKargono_1_1Network_1_1SessionInitCache" ],
        [ "Session", "classKargono_1_1Network_1_1Session.html", "classKargono_1_1Network_1_1Session" ],
        [ "TCPConnection", "classKargono_1_1Network_1_1TCPConnection.html", "classKargono_1_1Network_1_1TCPConnection" ],
        [ "UDPConnection", "classKargono_1_1Network_1_1UDPConnection.html", "classKargono_1_1Network_1_1UDPConnection" ]
      ] ],
      [ "Panels", "namespaceKargono_1_1Panels.html", [
        [ "ContentBrowserPanel", "classKargono_1_1Panels_1_1ContentBrowserPanel.html", "classKargono_1_1Panels_1_1ContentBrowserPanel" ],
        [ "EntityClassEditor", "classKargono_1_1Panels_1_1EntityClassEditor.html", "classKargono_1_1Panels_1_1EntityClassEditor" ],
        [ "GameStatePanel", "classKargono_1_1Panels_1_1GameStatePanel.html", "classKargono_1_1Panels_1_1GameStatePanel" ],
        [ "InputModePanel", "classKargono_1_1Panels_1_1InputModePanel.html", "classKargono_1_1Panels_1_1InputModePanel" ],
        [ "ImGuiLog", "structKargono_1_1Panels_1_1ImGuiLog.html", "structKargono_1_1Panels_1_1ImGuiLog" ],
        [ "LogPanel", "classKargono_1_1Panels_1_1LogPanel.html", "classKargono_1_1Panels_1_1LogPanel" ],
        [ "ProjectPanel", "classKargono_1_1Panels_1_1ProjectPanel.html", "classKargono_1_1Panels_1_1ProjectPanel" ],
        [ "PropertiesPanel", "classKargono_1_1Panels_1_1PropertiesPanel.html", "classKargono_1_1Panels_1_1PropertiesPanel" ],
        [ "SceneHierarchyPanel", "classKargono_1_1Panels_1_1SceneHierarchyPanel.html", "classKargono_1_1Panels_1_1SceneHierarchyPanel" ],
        [ "ScriptEditorPanel", "classKargono_1_1Panels_1_1ScriptEditorPanel.html", "classKargono_1_1Panels_1_1ScriptEditorPanel" ],
        [ "StatisticsPanel", "classKargono_1_1Panels_1_1StatisticsPanel.html", "classKargono_1_1Panels_1_1StatisticsPanel" ],
        [ "TestingPanel", "classKargono_1_1Panels_1_1TestingPanel.html", "classKargono_1_1Panels_1_1TestingPanel" ],
        [ "TextEditorPanel", "classKargono_1_1Panels_1_1TextEditorPanel.html", "classKargono_1_1Panels_1_1TextEditorPanel" ],
        [ "UIEditorPanel", "classKargono_1_1Panels_1_1UIEditorPanel.html", "classKargono_1_1Panels_1_1UIEditorPanel" ],
        [ "ViewportPanel", "classKargono_1_1Panels_1_1ViewportPanel.html", "classKargono_1_1Panels_1_1ViewportPanel" ]
      ] ],
      [ "Physics", "namespaceKargono_1_1Physics.html", [
        [ "ContactListener", "classKargono_1_1Physics_1_1ContactListener.html", "classKargono_1_1Physics_1_1ContactListener" ],
        [ "PhysicsSpecification", "structKargono_1_1Physics_1_1PhysicsSpecification.html", "structKargono_1_1Physics_1_1PhysicsSpecification" ],
        [ "Physics2DWorld", "classKargono_1_1Physics_1_1Physics2DWorld.html", "classKargono_1_1Physics_1_1Physics2DWorld" ]
      ] ],
      [ "Projects", "namespaceKargono_1_1Projects.html", [
        [ "Project", "classKargono_1_1Projects_1_1Project.html", "classKargono_1_1Projects_1_1Project" ],
        [ "ProjectService", "classKargono_1_1Projects_1_1ProjectService.html", "classKargono_1_1Projects_1_1ProjectService" ]
      ] ],
      [ "Rendering", "namespaceKargono_1_1Rendering.html", [
        [ "Camera", "classKargono_1_1Rendering_1_1Camera.html", "classKargono_1_1Rendering_1_1Camera" ],
        [ "EditorCamera", "classKargono_1_1Rendering_1_1EditorCamera.html", "classKargono_1_1Rendering_1_1EditorCamera" ],
        [ "FramebufferDataSpecification", "structKargono_1_1Rendering_1_1FramebufferDataSpecification.html", "structKargono_1_1Rendering_1_1FramebufferDataSpecification" ],
        [ "FramebufferAttachmentSpecification", "structKargono_1_1Rendering_1_1FramebufferAttachmentSpecification.html", "structKargono_1_1Rendering_1_1FramebufferAttachmentSpecification" ],
        [ "FramebufferSpecification", "structKargono_1_1Rendering_1_1FramebufferSpecification.html", "structKargono_1_1Rendering_1_1FramebufferSpecification" ],
        [ "Framebuffer", "classKargono_1_1Rendering_1_1Framebuffer.html", "classKargono_1_1Rendering_1_1Framebuffer" ],
        [ "InputBufferElement", "structKargono_1_1Rendering_1_1InputBufferElement.html", "structKargono_1_1Rendering_1_1InputBufferElement" ],
        [ "InputBufferLayout", "classKargono_1_1Rendering_1_1InputBufferLayout.html", "classKargono_1_1Rendering_1_1InputBufferLayout" ],
        [ "VertexBuffer", "classKargono_1_1Rendering_1_1VertexBuffer.html", "classKargono_1_1Rendering_1_1VertexBuffer" ],
        [ "IndexBuffer", "classKargono_1_1Rendering_1_1IndexBuffer.html", "classKargono_1_1Rendering_1_1IndexBuffer" ],
        [ "RendererAPI", "classKargono_1_1Rendering_1_1RendererAPI.html", null ],
        [ "RenderingService", "classKargono_1_1Rendering_1_1RenderingService.html", "classKargono_1_1Rendering_1_1RenderingService" ],
        [ "DrawCallBuffer", "structKargono_1_1Rendering_1_1DrawCallBuffer.html", "structKargono_1_1Rendering_1_1DrawCallBuffer" ],
        [ "RendererInputSpec", "structKargono_1_1Rendering_1_1RendererInputSpec.html", "structKargono_1_1Rendering_1_1RendererInputSpec" ],
        [ "ShaderSpecification", "structKargono_1_1Rendering_1_1ShaderSpecification.html", "structKargono_1_1Rendering_1_1ShaderSpecification" ],
        [ "Shader", "classKargono_1_1Rendering_1_1Shader.html", "classKargono_1_1Rendering_1_1Shader" ],
        [ "ShaderBuilder", "classKargono_1_1Rendering_1_1ShaderBuilder.html", null ],
        [ "Shape", "classKargono_1_1Rendering_1_1Shape.html", "classKargono_1_1Rendering_1_1Shape" ],
        [ "TextureSpecification", "structKargono_1_1Rendering_1_1TextureSpecification.html", "structKargono_1_1Rendering_1_1TextureSpecification" ],
        [ "Texture", "classKargono_1_1Rendering_1_1Texture.html", "classKargono_1_1Rendering_1_1Texture" ],
        [ "Texture2D", "classKargono_1_1Rendering_1_1Texture2D.html", null ],
        [ "UniformElement", "structKargono_1_1Rendering_1_1UniformElement.html", "structKargono_1_1Rendering_1_1UniformElement" ],
        [ "UniformBufferList", "classKargono_1_1Rendering_1_1UniformBufferList.html", "classKargono_1_1Rendering_1_1UniformBufferList" ],
        [ "UniformBuffer", "classKargono_1_1Rendering_1_1UniformBuffer.html", "classKargono_1_1Rendering_1_1UniformBuffer" ],
        [ "VertexArray", "classKargono_1_1Rendering_1_1VertexArray.html", "classKargono_1_1Rendering_1_1VertexArray" ]
      ] ],
      [ "RuntimeUI", "namespaceKargono_1_1RuntimeUI.html", [
        [ "FontService", "classKargono_1_1RuntimeUI_1_1FontService.html", null ],
        [ "Character", "structKargono_1_1RuntimeUI_1_1Character.html", "structKargono_1_1RuntimeUI_1_1Character" ],
        [ "Font", "classKargono_1_1RuntimeUI_1_1Font.html", "classKargono_1_1RuntimeUI_1_1Font" ],
        [ "WidgetCallbacks", "structKargono_1_1RuntimeUI_1_1WidgetCallbacks.html", "structKargono_1_1RuntimeUI_1_1WidgetCallbacks" ],
        [ "UICallbacks", "structKargono_1_1RuntimeUI_1_1UICallbacks.html", "structKargono_1_1RuntimeUI_1_1UICallbacks" ],
        [ "DirectionPointers", "structKargono_1_1RuntimeUI_1_1DirectionPointers.html", "structKargono_1_1RuntimeUI_1_1DirectionPointers" ],
        [ "Widget", "classKargono_1_1RuntimeUI_1_1Widget.html", "classKargono_1_1RuntimeUI_1_1Widget" ],
        [ "TextWidget", "classKargono_1_1RuntimeUI_1_1TextWidget.html", "classKargono_1_1RuntimeUI_1_1TextWidget" ],
        [ "ButtonWidget", "classKargono_1_1RuntimeUI_1_1ButtonWidget.html", "classKargono_1_1RuntimeUI_1_1ButtonWidget" ],
        [ "CheckboxWidget", "classKargono_1_1RuntimeUI_1_1CheckboxWidget.html", "classKargono_1_1RuntimeUI_1_1CheckboxWidget" ],
        [ "ComboWidget", "classKargono_1_1RuntimeUI_1_1ComboWidget.html", "classKargono_1_1RuntimeUI_1_1ComboWidget" ],
        [ "PopupWidget", "classKargono_1_1RuntimeUI_1_1PopupWidget.html", "classKargono_1_1RuntimeUI_1_1PopupWidget" ],
        [ "Window", "structKargono_1_1RuntimeUI_1_1Window.html", "structKargono_1_1RuntimeUI_1_1Window" ],
        [ "UserInterface", "classKargono_1_1RuntimeUI_1_1UserInterface.html", "classKargono_1_1RuntimeUI_1_1UserInterface" ],
        [ "RuntimeUIService", "classKargono_1_1RuntimeUI_1_1RuntimeUIService.html", "classKargono_1_1RuntimeUI_1_1RuntimeUIService" ]
      ] ],
      [ "Scenes", "namespaceKargono_1_1Scenes.html", [
        [ "IDComponent", "structKargono_1_1Scenes_1_1IDComponent.html", "structKargono_1_1Scenes_1_1IDComponent" ],
        [ "TagComponent", "structKargono_1_1Scenes_1_1TagComponent.html", "structKargono_1_1Scenes_1_1TagComponent" ],
        [ "TransformComponent", "structKargono_1_1Scenes_1_1TransformComponent.html", "structKargono_1_1Scenes_1_1TransformComponent" ],
        [ "CameraComponent", "structKargono_1_1Scenes_1_1CameraComponent.html", "structKargono_1_1Scenes_1_1CameraComponent" ],
        [ "NetworkComponent", "structKargono_1_1Scenes_1_1NetworkComponent.html", "structKargono_1_1Scenes_1_1NetworkComponent" ],
        [ "Rigidbody2DComponent", "structKargono_1_1Scenes_1_1Rigidbody2DComponent.html", "structKargono_1_1Scenes_1_1Rigidbody2DComponent" ],
        [ "BoxCollider2DComponent", "structKargono_1_1Scenes_1_1BoxCollider2DComponent.html", "structKargono_1_1Scenes_1_1BoxCollider2DComponent" ],
        [ "ClassInstanceComponent", "structKargono_1_1Scenes_1_1ClassInstanceComponent.html", "structKargono_1_1Scenes_1_1ClassInstanceComponent" ],
        [ "CircleCollider2DComponent", "structKargono_1_1Scenes_1_1CircleCollider2DComponent.html", "structKargono_1_1Scenes_1_1CircleCollider2DComponent" ],
        [ "ShapeComponent", "structKargono_1_1Scenes_1_1ShapeComponent.html", "structKargono_1_1Scenes_1_1ShapeComponent" ],
        [ "ComponentGroup", "structKargono_1_1Scenes_1_1ComponentGroup.html", null ],
        [ "Entity", "classKargono_1_1Scenes_1_1Entity.html", "classKargono_1_1Scenes_1_1Entity" ],
        [ "EntityScripts", "structKargono_1_1Scenes_1_1EntityScripts.html", "structKargono_1_1Scenes_1_1EntityScripts" ],
        [ "ClassField", "structKargono_1_1Scenes_1_1ClassField.html", "structKargono_1_1Scenes_1_1ClassField" ],
        [ "EntityClass", "classKargono_1_1Scenes_1_1EntityClass.html", "classKargono_1_1Scenes_1_1EntityClass" ],
        [ "GameState", "classKargono_1_1Scenes_1_1GameState.html", "classKargono_1_1Scenes_1_1GameState" ],
        [ "GameStateService", "classKargono_1_1Scenes_1_1GameStateService.html", null ],
        [ "Scene", "classKargono_1_1Scenes_1_1Scene.html", "classKargono_1_1Scenes_1_1Scene" ],
        [ "SceneService", "classKargono_1_1Scenes_1_1SceneService.html", null ],
        [ "SceneCamera", "classKargono_1_1Scenes_1_1SceneCamera.html", "classKargono_1_1Scenes_1_1SceneCamera" ]
      ] ],
      [ "Scripting", "namespaceKargono_1_1Scripting.html", [
        [ "ScriptToken", "structKargono_1_1Scripting_1_1ScriptToken.html", "structKargono_1_1Scripting_1_1ScriptToken" ],
        [ "ScriptTokenizer", "classKargono_1_1Scripting_1_1ScriptTokenizer.html", "classKargono_1_1Scripting_1_1ScriptTokenizer" ],
        [ "StatementEmpty", "structKargono_1_1Scripting_1_1StatementEmpty.html", null ],
        [ "StatementLiteral", "structKargono_1_1Scripting_1_1StatementLiteral.html", "structKargono_1_1Scripting_1_1StatementLiteral" ],
        [ "StatementDeclaration", "structKargono_1_1Scripting_1_1StatementDeclaration.html", "structKargono_1_1Scripting_1_1StatementDeclaration" ],
        [ "StatementAssignment", "structKargono_1_1Scripting_1_1StatementAssignment.html", "structKargono_1_1Scripting_1_1StatementAssignment" ],
        [ "FunctionParameter", "structKargono_1_1Scripting_1_1FunctionParameter.html", "structKargono_1_1Scripting_1_1FunctionParameter" ],
        [ "FunctionNode", "structKargono_1_1Scripting_1_1FunctionNode.html", "structKargono_1_1Scripting_1_1FunctionNode" ],
        [ "ProgramNode", "structKargono_1_1Scripting_1_1ProgramNode.html", "structKargono_1_1Scripting_1_1ProgramNode" ],
        [ "ScriptAST", "structKargono_1_1Scripting_1_1ScriptAST.html", "structKargono_1_1Scripting_1_1ScriptAST" ],
        [ "ParserError", "structKargono_1_1Scripting_1_1ParserError.html", "structKargono_1_1Scripting_1_1ParserError" ],
        [ "TokenParser", "classKargono_1_1Scripting_1_1TokenParser.html", "classKargono_1_1Scripting_1_1TokenParser" ],
        [ "ScriptCompiler", "classKargono_1_1Scripting_1_1ScriptCompiler.html", null ],
        [ "ScriptService", "classKargono_1_1Scripting_1_1ScriptService.html", null ],
        [ "Script", "classKargono_1_1Scripting_1_1Script.html", "classKargono_1_1Scripting_1_1Script" ],
        [ "ScriptModuleBuilder", "classKargono_1_1Scripting_1_1ScriptModuleBuilder.html", "classKargono_1_1Scripting_1_1ScriptModuleBuilder" ]
      ] ],
      [ "Utility", "namespaceKargono_1_1Utility.html", [
        [ "Conversions", "classKargono_1_1Utility_1_1Conversions.html", "classKargono_1_1Utility_1_1Conversions" ],
        [ "FileDialogs", "classKargono_1_1Utility_1_1FileDialogs.html", null ],
        [ "FileSystem", "classKargono_1_1Utility_1_1FileSystem.html", null ],
        [ "Operations", "classKargono_1_1Utility_1_1Operations.html", null ],
        [ "OSCommands", "classKargono_1_1Utility_1_1OSCommands.html", null ],
        [ "RandomService", "classKargono_1_1Utility_1_1RandomService.html", null ],
        [ "Regex", "classKargono_1_1Utility_1_1Regex.html", null ],
        [ "Time", "classKargono_1_1Utility_1_1Time.html", null ],
        [ "ScopedTimer", "classKargono_1_1Utility_1_1ScopedTimer.html", "classKargono_1_1Utility_1_1ScopedTimer" ],
        [ "AsyncBusyTimer", "classKargono_1_1Utility_1_1AsyncBusyTimer.html", "classKargono_1_1Utility_1_1AsyncBusyTimer" ]
      ] ],
      [ "RuntimeApp", "classKargono_1_1RuntimeApp.html", "classKargono_1_1RuntimeApp" ],
      [ "Application", "classKargono_1_1Application.html", "classKargono_1_1Application" ],
      [ "AppTickGenerator", "structKargono_1_1AppTickGenerator.html", "structKargono_1_1AppTickGenerator" ],
      [ "AppTickService", "classKargono_1_1AppTickService.html", null ],
      [ "TestingException", "classKargono_1_1TestingException.html", "classKargono_1_1TestingException" ],
      [ "Buffer", "structKargono_1_1Buffer.html", "structKargono_1_1Buffer" ],
      [ "TSQueue", "classKargono_1_1TSQueue.html", "classKargono_1_1TSQueue" ],
      [ "CommandLineArguments", "structKargono_1_1CommandLineArguments.html", "structKargono_1_1CommandLineArguments" ],
      [ "EngineSpec", "structKargono_1_1EngineSpec.html", "structKargono_1_1EngineSpec" ],
      [ "Engine", "classKargono_1_1Engine.html", "classKargono_1_1Engine" ],
      [ "EngineService", "classKargono_1_1EngineService.html", null ],
      [ "Log", "classKargono_1_1Log.html", null ],
      [ "Timestep", "classKargono_1_1Timestep.html", "classKargono_1_1Timestep" ],
      [ "UUID", "classKargono_1_1UUID.html", "classKargono_1_1UUID" ],
      [ "WindowProps", "structKargono_1_1WindowProps.html", "structKargono_1_1WindowProps" ],
      [ "Window", "classKargono_1_1Window.html", "classKargono_1_1Window" ],
      [ "WrappedVariable", "classKargono_1_1WrappedVariable.html", "classKargono_1_1WrappedVariable" ],
      [ "WrappedInteger32", "classKargono_1_1WrappedInteger32.html", "classKargono_1_1WrappedInteger32" ],
      [ "WrappedUInteger16", "classKargono_1_1WrappedUInteger16.html", "classKargono_1_1WrappedUInteger16" ],
      [ "WrappedUInteger32", "classKargono_1_1WrappedUInteger32.html", "classKargono_1_1WrappedUInteger32" ],
      [ "WrappedUInteger64", "classKargono_1_1WrappedUInteger64.html", "classKargono_1_1WrappedUInteger64" ],
      [ "WrappedVector3", "classKargono_1_1WrappedVector3.html", "classKargono_1_1WrappedVector3" ],
      [ "WrappedString", "classKargono_1_1WrappedString.html", "classKargono_1_1WrappedString" ],
      [ "WrappedBool", "classKargono_1_1WrappedBool.html", "classKargono_1_1WrappedBool" ],
      [ "WrappedFloat", "classKargono_1_1WrappedFloat.html", "classKargono_1_1WrappedFloat" ],
      [ "WrappedFunction", "classKargono_1_1WrappedFunction.html", "classKargono_1_1WrappedFunction" ],
      [ "WrappedVoidNone", "classKargono_1_1WrappedVoidNone.html", "classKargono_1_1WrappedVoidNone" ],
      [ "WrappedVoidString", "classKargono_1_1WrappedVoidString.html", "classKargono_1_1WrappedVoidString" ],
      [ "WrappedVoidFloat", "classKargono_1_1WrappedVoidFloat.html", "classKargono_1_1WrappedVoidFloat" ],
      [ "WrappedVoidUInt16", "classKargono_1_1WrappedVoidUInt16.html", "classKargono_1_1WrappedVoidUInt16" ],
      [ "WrappedVoidUInt32", "classKargono_1_1WrappedVoidUInt32.html", "classKargono_1_1WrappedVoidUInt32" ],
      [ "WrappedVoidUInt64", "classKargono_1_1WrappedVoidUInt64.html", "classKargono_1_1WrappedVoidUInt64" ],
      [ "WrappedVoidUInt64Float", "classKargono_1_1WrappedVoidUInt64Float.html", "classKargono_1_1WrappedVoidUInt64Float" ],
      [ "WrappedBoolNone", "classKargono_1_1WrappedBoolNone.html", "classKargono_1_1WrappedBoolNone" ],
      [ "WrappedBoolUInt64", "classKargono_1_1WrappedBoolUInt64.html", "classKargono_1_1WrappedBoolUInt64" ],
      [ "WrappedBoolUInt64UInt64", "classKargono_1_1WrappedBoolUInt64UInt64.html", "classKargono_1_1WrappedBoolUInt64UInt64" ],
      [ "WrappedBoolUInt64UInt16UInt64", "classKargono_1_1WrappedBoolUInt64UInt16UInt64.html", "classKargono_1_1WrappedBoolUInt64UInt16UInt64" ],
      [ "ServerApp", "classKargono_1_1ServerApp.html", "classKargono_1_1ServerApp" ],
      [ "EditorApp", "classKargono_1_1EditorApp.html", "classKargono_1_1EditorApp" ],
      [ "LauncherApp", "classKargono_1_1LauncherApp.html", "classKargono_1_1LauncherApp" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< Kargono::UUID >", "structstd_1_1hash_3_01Kargono_1_1UUID_01_4.html", "structstd_1_1hash_3_01Kargono_1_1UUID_01_4" ]
    ] ],
    [ "YAML", "namespaceYAML.html", [
      [ "convert< Kargono::Math::vec2 >", "structYAML_1_1convert_3_01Kargono_1_1Math_1_1vec2_01_4.html", null ],
      [ "convert< Kargono::Math::vec3 >", "structYAML_1_1convert_3_01Kargono_1_1Math_1_1vec3_01_4.html", null ],
      [ "convert< Kargono::Math::vec4 >", "structYAML_1_1convert_3_01Kargono_1_1Math_1_1vec4_01_4.html", null ],
      [ "convert< Kargono::Math::ivec2 >", "structYAML_1_1convert_3_01Kargono_1_1Math_1_1ivec2_01_4.html", null ],
      [ "convert< Kargono::Math::ivec3 >", "structYAML_1_1convert_3_01Kargono_1_1Math_1_1ivec3_01_4.html", null ],
      [ "convert< Kargono::Math::ivec4 >", "structYAML_1_1convert_3_01Kargono_1_1Math_1_1ivec4_01_4.html", null ],
      [ "convert< Kargono::UUID >", "structYAML_1_1convert_3_01Kargono_1_1UUID_01_4.html", null ]
    ] ]
];