var annotated_dup =
[
    [ "Kargono", "namespaceKargono.html", [
      [ "AI", "namespaceKargono_1_1AI.html", [
        [ "AIContext", "structKargono_1_1AI_1_1AIContext.html", "structKargono_1_1AI_1_1AIContext" ],
        [ "AIMessage", "structKargono_1_1AI_1_1AIMessage.html", "structKargono_1_1AI_1_1AIMessage" ],
        [ "AIService", "classKargono_1_1AI_1_1AIService.html", null ],
        [ "AIState", "structKargono_1_1AI_1_1AIState.html", "structKargono_1_1AI_1_1AIState" ]
      ] ],
      [ "Assets", "namespaceKargono_1_1Assets.html", [
        [ "AIStateManager", "classKargono_1_1Assets_1_1AIStateManager.html", "classKargono_1_1Assets_1_1AIStateManager" ],
        [ "AIStateMetaData", "structKargono_1_1Assets_1_1AIStateMetaData.html", null ],
        [ "AssetInfo", "structKargono_1_1Assets_1_1AssetInfo.html", "structKargono_1_1Assets_1_1AssetInfo" ],
        [ "AssetManager", "classKargono_1_1Assets_1_1AssetManager.html", "classKargono_1_1Assets_1_1AssetManager" ],
        [ "AssetsContext", "structKargono_1_1Assets_1_1AssetsContext.html", "structKargono_1_1Assets_1_1AssetsContext" ],
        [ "AssetService", "classKargono_1_1Assets_1_1AssetService.html", null ],
        [ "AudioBufferManager", "classKargono_1_1Assets_1_1AudioBufferManager.html", "classKargono_1_1Assets_1_1AudioBufferManager" ],
        [ "AudioMetaData", "structKargono_1_1Assets_1_1AudioMetaData.html", "structKargono_1_1Assets_1_1AudioMetaData" ],
        [ "EmitterConfigManager", "classKargono_1_1Assets_1_1EmitterConfigManager.html", "classKargono_1_1Assets_1_1EmitterConfigManager" ],
        [ "FieldReallocationInstructions", "structKargono_1_1Assets_1_1FieldReallocationInstructions.html", "structKargono_1_1Assets_1_1FieldReallocationInstructions" ],
        [ "FontManager", "classKargono_1_1Assets_1_1FontManager.html", "classKargono_1_1Assets_1_1FontManager" ],
        [ "FontMetaData", "structKargono_1_1Assets_1_1FontMetaData.html", "structKargono_1_1Assets_1_1FontMetaData" ],
        [ "GameStateManager", "classKargono_1_1Assets_1_1GameStateManager.html", "classKargono_1_1Assets_1_1GameStateManager" ],
        [ "GameStateMetaData", "structKargono_1_1Assets_1_1GameStateMetaData.html", "structKargono_1_1Assets_1_1GameStateMetaData" ],
        [ "InputMapManager", "classKargono_1_1Assets_1_1InputMapManager.html", "classKargono_1_1Assets_1_1InputMapManager" ],
        [ "InputMapMetaData", "structKargono_1_1Assets_1_1InputMapMetaData.html", null ],
        [ "Metadata", "structKargono_1_1Assets_1_1Metadata.html", "structKargono_1_1Assets_1_1Metadata" ],
        [ "ParticleEmitterConfigMetaData", "structKargono_1_1Assets_1_1ParticleEmitterConfigMetaData.html", null ],
        [ "ProjectComponentManager", "classKargono_1_1Assets_1_1ProjectComponentManager.html", "classKargono_1_1Assets_1_1ProjectComponentManager" ],
        [ "ProjectComponentMetaData", "structKargono_1_1Assets_1_1ProjectComponentMetaData.html", "structKargono_1_1Assets_1_1ProjectComponentMetaData" ],
        [ "SceneManager", "classKargono_1_1Assets_1_1SceneManager.html", "classKargono_1_1Assets_1_1SceneManager" ],
        [ "SceneMetaData", "structKargono_1_1Assets_1_1SceneMetaData.html", null ],
        [ "ScriptManager", "classKargono_1_1Assets_1_1ScriptManager.html", "classKargono_1_1Assets_1_1ScriptManager" ],
        [ "ScriptMetaData", "structKargono_1_1Assets_1_1ScriptMetaData.html", "structKargono_1_1Assets_1_1ScriptMetaData" ],
        [ "ScriptSpec", "structKargono_1_1Assets_1_1ScriptSpec.html", "structKargono_1_1Assets_1_1ScriptSpec" ],
        [ "ShaderManager", "classKargono_1_1Assets_1_1ShaderManager.html", "classKargono_1_1Assets_1_1ShaderManager" ],
        [ "ShaderMetaData", "structKargono_1_1Assets_1_1ShaderMetaData.html", "structKargono_1_1Assets_1_1ShaderMetaData" ],
        [ "Texture2DManager", "classKargono_1_1Assets_1_1Texture2DManager.html", "classKargono_1_1Assets_1_1Texture2DManager" ],
        [ "TextureMetaData", "structKargono_1_1Assets_1_1TextureMetaData.html", "structKargono_1_1Assets_1_1TextureMetaData" ],
        [ "UserInterfaceManager", "classKargono_1_1Assets_1_1UserInterfaceManager.html", "classKargono_1_1Assets_1_1UserInterfaceManager" ],
        [ "UserInterfaceMetaData", "structKargono_1_1Assets_1_1UserInterfaceMetaData.html", null ]
      ] ],
      [ "Audio", "namespaceKargono_1_1Audio.html", [
        [ "AudioBuffer", "classKargono_1_1Audio_1_1AudioBuffer.html", "classKargono_1_1Audio_1_1AudioBuffer" ],
        [ "AudioContext", "structKargono_1_1Audio_1_1AudioContext.html", "structKargono_1_1Audio_1_1AudioContext" ],
        [ "AudioListener", "classKargono_1_1Audio_1_1AudioListener.html", "classKargono_1_1Audio_1_1AudioListener" ],
        [ "AudioListenerSpecification", "structKargono_1_1Audio_1_1AudioListenerSpecification.html", "structKargono_1_1Audio_1_1AudioListenerSpecification" ],
        [ "AudioService", "classKargono_1_1Audio_1_1AudioService.html", "classKargono_1_1Audio_1_1AudioService" ],
        [ "AudioSource", "classKargono_1_1Audio_1_1AudioSource.html", "classKargono_1_1Audio_1_1AudioSource" ],
        [ "AudioSourceSpecification", "structKargono_1_1Audio_1_1AudioSourceSpecification.html", "structKargono_1_1Audio_1_1AudioSourceSpecification" ]
      ] ],
      [ "ECS", "namespaceKargono_1_1ECS.html", [
        [ "AIStateComponent", "structKargono_1_1ECS_1_1AIStateComponent.html", "structKargono_1_1ECS_1_1AIStateComponent" ],
        [ "BoxCollider2DComponent", "structKargono_1_1ECS_1_1BoxCollider2DComponent.html", "structKargono_1_1ECS_1_1BoxCollider2DComponent" ],
        [ "CameraComponent", "structKargono_1_1ECS_1_1CameraComponent.html", "structKargono_1_1ECS_1_1CameraComponent" ],
        [ "CircleCollider2DComponent", "structKargono_1_1ECS_1_1CircleCollider2DComponent.html", "structKargono_1_1ECS_1_1CircleCollider2DComponent" ],
        [ "ComponentGroup", "structKargono_1_1ECS_1_1ComponentGroup.html", null ],
        [ "Entity", "classKargono_1_1ECS_1_1Entity.html", "classKargono_1_1ECS_1_1Entity" ],
        [ "EntityRegistry", "structKargono_1_1ECS_1_1EntityRegistry.html", "structKargono_1_1ECS_1_1EntityRegistry" ],
        [ "EntityRegistryService", "classKargono_1_1ECS_1_1EntityRegistryService.html", null ],
        [ "IDComponent", "structKargono_1_1ECS_1_1IDComponent.html", "structKargono_1_1ECS_1_1IDComponent" ],
        [ "NetworkComponent", "structKargono_1_1ECS_1_1NetworkComponent.html", "structKargono_1_1ECS_1_1NetworkComponent" ],
        [ "OnCreateComponent", "structKargono_1_1ECS_1_1OnCreateComponent.html", "structKargono_1_1ECS_1_1OnCreateComponent" ],
        [ "OnUpdateComponent", "structKargono_1_1ECS_1_1OnUpdateComponent.html", "structKargono_1_1ECS_1_1OnUpdateComponent" ],
        [ "ParticleEmitterComponent", "structKargono_1_1ECS_1_1ParticleEmitterComponent.html", "structKargono_1_1ECS_1_1ParticleEmitterComponent" ],
        [ "ProjectComponent", "structKargono_1_1ECS_1_1ProjectComponent.html", "structKargono_1_1ECS_1_1ProjectComponent" ],
        [ "ProjectComponentService", "classKargono_1_1ECS_1_1ProjectComponentService.html", null ],
        [ "ProjectComponentStorage", "structKargono_1_1ECS_1_1ProjectComponentStorage.html", "structKargono_1_1ECS_1_1ProjectComponentStorage" ],
        [ "Rigidbody2DComponent", "structKargono_1_1ECS_1_1Rigidbody2DComponent.html", "structKargono_1_1ECS_1_1Rigidbody2DComponent" ],
        [ "ShapeComponent", "structKargono_1_1ECS_1_1ShapeComponent.html", "structKargono_1_1ECS_1_1ShapeComponent" ],
        [ "TagComponent", "structKargono_1_1ECS_1_1TagComponent.html", "structKargono_1_1ECS_1_1TagComponent" ],
        [ "TransformComponent", "structKargono_1_1ECS_1_1TransformComponent.html", "structKargono_1_1ECS_1_1TransformComponent" ]
      ] ],
      [ "EditorUI", "namespaceKargono_1_1EditorUI.html", [
        [ "CheckboxSpec", "structKargono_1_1EditorUI_1_1CheckboxSpec.html", "structKargono_1_1EditorUI_1_1CheckboxSpec" ],
        [ "ChooseDirectorySpec", "structKargono_1_1EditorUI_1_1ChooseDirectorySpec.html", "structKargono_1_1EditorUI_1_1ChooseDirectorySpec" ],
        [ "CollapsingHeaderSpec", "structKargono_1_1EditorUI_1_1CollapsingHeaderSpec.html", "structKargono_1_1EditorUI_1_1CollapsingHeaderSpec" ],
        [ "DragDropPayload", "structKargono_1_1EditorUI_1_1DragDropPayload.html", "structKargono_1_1EditorUI_1_1DragDropPayload" ],
        [ "EditFloatSpec", "structKargono_1_1EditorUI_1_1EditFloatSpec.html", "structKargono_1_1EditorUI_1_1EditFloatSpec" ],
        [ "EditIntegerSpec", "structKargono_1_1EditorUI_1_1EditIntegerSpec.html", "structKargono_1_1EditorUI_1_1EditIntegerSpec" ],
        [ "EditIVec2Spec", "structKargono_1_1EditorUI_1_1EditIVec2Spec.html", "structKargono_1_1EditorUI_1_1EditIVec2Spec" ],
        [ "EditMultiLineTextSpec", "structKargono_1_1EditorUI_1_1EditMultiLineTextSpec.html", "structKargono_1_1EditorUI_1_1EditMultiLineTextSpec" ],
        [ "EditorUIService", "classKargono_1_1EditorUI_1_1EditorUIService.html", null ],
        [ "EditTextSpec", "structKargono_1_1EditorUI_1_1EditTextSpec.html", "structKargono_1_1EditorUI_1_1EditTextSpec" ],
        [ "EditVariableSpec", "structKargono_1_1EditorUI_1_1EditVariableSpec.html", "structKargono_1_1EditorUI_1_1EditVariableSpec" ],
        [ "EditVec2Spec", "structKargono_1_1EditorUI_1_1EditVec2Spec.html", "structKargono_1_1EditorUI_1_1EditVec2Spec" ],
        [ "EditVec3Spec", "structKargono_1_1EditorUI_1_1EditVec3Spec.html", "structKargono_1_1EditorUI_1_1EditVec3Spec" ],
        [ "EditVec4Spec", "structKargono_1_1EditorUI_1_1EditVec4Spec.html", "structKargono_1_1EditorUI_1_1EditVec4Spec" ],
        [ "GenericPopupSpec", "structKargono_1_1EditorUI_1_1GenericPopupSpec.html", "structKargono_1_1EditorUI_1_1GenericPopupSpec" ],
        [ "GridEntry", "structKargono_1_1EditorUI_1_1GridEntry.html", "structKargono_1_1EditorUI_1_1GridEntry" ],
        [ "GridEntryArchetype", "structKargono_1_1EditorUI_1_1GridEntryArchetype.html", "structKargono_1_1EditorUI_1_1GridEntryArchetype" ],
        [ "GridSpec", "structKargono_1_1EditorUI_1_1GridSpec.html", "structKargono_1_1EditorUI_1_1GridSpec" ],
        [ "InlineButtonSpec", "structKargono_1_1EditorUI_1_1InlineButtonSpec.html", "structKargono_1_1EditorUI_1_1InlineButtonSpec" ],
        [ "ListEntry", "structKargono_1_1EditorUI_1_1ListEntry.html", "structKargono_1_1EditorUI_1_1ListEntry" ],
        [ "ListSpec", "structKargono_1_1EditorUI_1_1ListSpec.html", "structKargono_1_1EditorUI_1_1ListSpec" ],
        [ "NavigationHeaderSpec", "structKargono_1_1EditorUI_1_1NavigationHeaderSpec.html", "structKargono_1_1EditorUI_1_1NavigationHeaderSpec" ],
        [ "OptionEntry", "structKargono_1_1EditorUI_1_1OptionEntry.html", "structKargono_1_1EditorUI_1_1OptionEntry" ],
        [ "PanelHeaderSpec", "structKargono_1_1EditorUI_1_1PanelHeaderSpec.html", "structKargono_1_1EditorUI_1_1PanelHeaderSpec" ],
        [ "RadioSelectorSpec", "structKargono_1_1EditorUI_1_1RadioSelectorSpec.html", "structKargono_1_1EditorUI_1_1RadioSelectorSpec" ],
        [ "SelectionEntry", "structKargono_1_1EditorUI_1_1SelectionEntry.html", "structKargono_1_1EditorUI_1_1SelectionEntry" ],
        [ "SelectOptionSpec", "structKargono_1_1EditorUI_1_1SelectOptionSpec.html", "structKargono_1_1EditorUI_1_1SelectOptionSpec" ],
        [ "TooltipEntry", "structKargono_1_1EditorUI_1_1TooltipEntry.html", "structKargono_1_1EditorUI_1_1TooltipEntry" ],
        [ "TooltipSeperatorData", "structKargono_1_1EditorUI_1_1TooltipSeperatorData.html", "structKargono_1_1EditorUI_1_1TooltipSeperatorData" ],
        [ "TooltipSpec", "structKargono_1_1EditorUI_1_1TooltipSpec.html", "structKargono_1_1EditorUI_1_1TooltipSpec" ],
        [ "TreeEntry", "structKargono_1_1EditorUI_1_1TreeEntry.html", "structKargono_1_1EditorUI_1_1TreeEntry" ],
        [ "TreePath", "classKargono_1_1EditorUI_1_1TreePath.html", "classKargono_1_1EditorUI_1_1TreePath" ],
        [ "TreeSpec", "structKargono_1_1EditorUI_1_1TreeSpec.html", "structKargono_1_1EditorUI_1_1TreeSpec" ],
        [ "WarningPopupSpec", "structKargono_1_1EditorUI_1_1WarningPopupSpec.html", "structKargono_1_1EditorUI_1_1WarningPopupSpec" ]
      ] ],
      [ "Events", "namespaceKargono_1_1Events.html", [
        [ "AddExtraUpdateEvent", "classKargono_1_1Events_1_1AddExtraUpdateEvent.html", "classKargono_1_1Events_1_1AddExtraUpdateEvent" ],
        [ "AddTickGeneratorUsage", "classKargono_1_1Events_1_1AddTickGeneratorUsage.html", "classKargono_1_1Events_1_1AddTickGeneratorUsage" ],
        [ "ApplicationCloseEvent", "classKargono_1_1Events_1_1ApplicationCloseEvent.html", "classKargono_1_1Events_1_1ApplicationCloseEvent" ],
        [ "ApplicationResizeEvent", "classKargono_1_1Events_1_1ApplicationResizeEvent.html", "classKargono_1_1Events_1_1ApplicationResizeEvent" ],
        [ "ApproveJoinSession", "classKargono_1_1Events_1_1ApproveJoinSession.html", "classKargono_1_1Events_1_1ApproveJoinSession" ],
        [ "AppTickEvent", "classKargono_1_1Events_1_1AppTickEvent.html", "classKargono_1_1Events_1_1AppTickEvent" ],
        [ "CleanUpTimersEvent", "classKargono_1_1Events_1_1CleanUpTimersEvent.html", "classKargono_1_1Events_1_1CleanUpTimersEvent" ],
        [ "ConnectionTerminated", "classKargono_1_1Events_1_1ConnectionTerminated.html", "classKargono_1_1Events_1_1ConnectionTerminated" ],
        [ "CurrentSessionInit", "classKargono_1_1Events_1_1CurrentSessionInit.html", "classKargono_1_1Events_1_1CurrentSessionInit" ],
        [ "DebugLineData", "structKargono_1_1Events_1_1DebugLineData.html", "structKargono_1_1Events_1_1DebugLineData" ],
        [ "DebugPointData", "structKargono_1_1Events_1_1DebugPointData.html", "structKargono_1_1Events_1_1DebugPointData" ],
        [ "DenyJoinSession", "classKargono_1_1Events_1_1DenyJoinSession.html", "classKargono_1_1Events_1_1DenyJoinSession" ],
        [ "EnableReadyCheck", "classKargono_1_1Events_1_1EnableReadyCheck.html", "classKargono_1_1Events_1_1EnableReadyCheck" ],
        [ "Event", "classKargono_1_1Events_1_1Event.html", "classKargono_1_1Events_1_1Event" ],
        [ "KeyPressedEvent", "classKargono_1_1Events_1_1KeyPressedEvent.html", "classKargono_1_1Events_1_1KeyPressedEvent" ],
        [ "KeyReleasedEvent", "classKargono_1_1Events_1_1KeyReleasedEvent.html", "classKargono_1_1Events_1_1KeyReleasedEvent" ],
        [ "KeyTypedEvent", "classKargono_1_1Events_1_1KeyTypedEvent.html", "classKargono_1_1Events_1_1KeyTypedEvent" ],
        [ "LeaveCurrentSession", "classKargono_1_1Events_1_1LeaveCurrentSession.html", "classKargono_1_1Events_1_1LeaveCurrentSession" ],
        [ "LogEvent", "classKargono_1_1Events_1_1LogEvent.html", "classKargono_1_1Events_1_1LogEvent" ],
        [ "ManageAsset", "classKargono_1_1Events_1_1ManageAsset.html", "classKargono_1_1Events_1_1ManageAsset" ],
        [ "ManageEditor", "classKargono_1_1Events_1_1ManageEditor.html", "classKargono_1_1Events_1_1ManageEditor" ],
        [ "ManageEntity", "classKargono_1_1Events_1_1ManageEntity.html", "classKargono_1_1Events_1_1ManageEntity" ],
        [ "ManageScene", "classKargono_1_1Events_1_1ManageScene.html", "classKargono_1_1Events_1_1ManageScene" ],
        [ "MouseButtonPressedEvent", "classKargono_1_1Events_1_1MouseButtonPressedEvent.html", "classKargono_1_1Events_1_1MouseButtonPressedEvent" ],
        [ "MouseButtonReleasedEvent", "classKargono_1_1Events_1_1MouseButtonReleasedEvent.html", "classKargono_1_1Events_1_1MouseButtonReleasedEvent" ],
        [ "MouseMovedEvent", "classKargono_1_1Events_1_1MouseMovedEvent.html", "classKargono_1_1Events_1_1MouseMovedEvent" ],
        [ "MouseScrolledEvent", "classKargono_1_1Events_1_1MouseScrolledEvent.html", "classKargono_1_1Events_1_1MouseScrolledEvent" ],
        [ "PhysicsCollisionEnd", "classKargono_1_1Events_1_1PhysicsCollisionEnd.html", "classKargono_1_1Events_1_1PhysicsCollisionEnd" ],
        [ "PhysicsCollisionStart", "classKargono_1_1Events_1_1PhysicsCollisionStart.html", "classKargono_1_1Events_1_1PhysicsCollisionStart" ],
        [ "ReceiveSignal", "classKargono_1_1Events_1_1ReceiveSignal.html", "classKargono_1_1Events_1_1ReceiveSignal" ],
        [ "RemoveTickGeneratorUsage", "classKargono_1_1Events_1_1RemoveTickGeneratorUsage.html", "classKargono_1_1Events_1_1RemoveTickGeneratorUsage" ],
        [ "RequestJoinSession", "classKargono_1_1Events_1_1RequestJoinSession.html", "classKargono_1_1Events_1_1RequestJoinSession" ],
        [ "RequestUserCount", "classKargono_1_1Events_1_1RequestUserCount.html", "classKargono_1_1Events_1_1RequestUserCount" ],
        [ "SendAllEntityLocation", "classKargono_1_1Events_1_1SendAllEntityLocation.html", "classKargono_1_1Events_1_1SendAllEntityLocation" ],
        [ "SendAllEntityPhysics", "classKargono_1_1Events_1_1SendAllEntityPhysics.html", "classKargono_1_1Events_1_1SendAllEntityPhysics" ],
        [ "SessionReadyCheck", "classKargono_1_1Events_1_1SessionReadyCheck.html", "classKargono_1_1Events_1_1SessionReadyCheck" ],
        [ "SessionReadyCheckConfirm", "classKargono_1_1Events_1_1SessionReadyCheckConfirm.html", "classKargono_1_1Events_1_1SessionReadyCheckConfirm" ],
        [ "SignalAll", "classKargono_1_1Events_1_1SignalAll.html", "classKargono_1_1Events_1_1SignalAll" ],
        [ "SkipUpdateEvent", "classKargono_1_1Events_1_1SkipUpdateEvent.html", "classKargono_1_1Events_1_1SkipUpdateEvent" ],
        [ "StartSession", "classKargono_1_1Events_1_1StartSession.html", "classKargono_1_1Events_1_1StartSession" ],
        [ "UpdateEntityLocation", "classKargono_1_1Events_1_1UpdateEntityLocation.html", "classKargono_1_1Events_1_1UpdateEntityLocation" ],
        [ "UpdateEntityPhysics", "classKargono_1_1Events_1_1UpdateEntityPhysics.html", "classKargono_1_1Events_1_1UpdateEntityPhysics" ],
        [ "UpdateOnlineUsers", "classKargono_1_1Events_1_1UpdateOnlineUsers.html", "classKargono_1_1Events_1_1UpdateOnlineUsers" ],
        [ "UpdateSessionUserSlot", "classKargono_1_1Events_1_1UpdateSessionUserSlot.html", "classKargono_1_1Events_1_1UpdateSessionUserSlot" ],
        [ "UserLeftSession", "classKargono_1_1Events_1_1UserLeftSession.html", "classKargono_1_1Events_1_1UserLeftSession" ],
        [ "WindowCloseEvent", "classKargono_1_1Events_1_1WindowCloseEvent.html", "classKargono_1_1Events_1_1WindowCloseEvent" ],
        [ "WindowResizeEvent", "classKargono_1_1Events_1_1WindowResizeEvent.html", "classKargono_1_1Events_1_1WindowResizeEvent" ]
      ] ],
      [ "Input", "namespaceKargono_1_1Input.html", [
        [ "InputActionBinding", "classKargono_1_1Input_1_1InputActionBinding.html", "classKargono_1_1Input_1_1InputActionBinding" ],
        [ "InputMap", "classKargono_1_1Input_1_1InputMap.html", "classKargono_1_1Input_1_1InputMap" ],
        [ "InputMapService", "classKargono_1_1Input_1_1InputMapService.html", null ],
        [ "InputService", "classKargono_1_1Input_1_1InputService.html", null ],
        [ "KeyboardActionBinding", "classKargono_1_1Input_1_1KeyboardActionBinding.html", "classKargono_1_1Input_1_1KeyboardActionBinding" ]
      ] ],
      [ "Math", "namespaceKargono_1_1Math.html", [
        [ "Interpolation", "classKargono_1_1Math_1_1Interpolation.html", null ],
        [ "Spline", "structKargono_1_1Math_1_1Spline.html", "structKargono_1_1Math_1_1Spline" ],
        [ "SplineService", "classKargono_1_1Math_1_1SplineService.html", null ]
      ] ],
      [ "Network", "namespaceKargono_1_1Network.html", [
        [ "Client", "classKargono_1_1Network_1_1Client.html", "classKargono_1_1Network_1_1Client" ],
        [ "ClientService", "classKargono_1_1Network_1_1ClientService.html", null ],
        [ "ClientTCPConnection", "classKargono_1_1Network_1_1ClientTCPConnection.html", "classKargono_1_1Network_1_1ClientTCPConnection" ],
        [ "ClientUDPConnection", "classKargono_1_1Network_1_1ClientUDPConnection.html", "classKargono_1_1Network_1_1ClientUDPConnection" ],
        [ "LabeledMessage", "structKargono_1_1Network_1_1LabeledMessage.html", "structKargono_1_1Network_1_1LabeledMessage" ],
        [ "Message", "structKargono_1_1Network_1_1Message.html", "structKargono_1_1Network_1_1Message" ],
        [ "MessageHeader", "structKargono_1_1Network_1_1MessageHeader.html", "structKargono_1_1Network_1_1MessageHeader" ],
        [ "NetworkContext", "structKargono_1_1Network_1_1NetworkContext.html", "structKargono_1_1Network_1_1NetworkContext" ],
        [ "owned_message", "structKargono_1_1Network_1_1owned__message.html", "structKargono_1_1Network_1_1owned__message" ],
        [ "Server", "classKargono_1_1Network_1_1Server.html", "classKargono_1_1Network_1_1Server" ],
        [ "ServerService", "classKargono_1_1Network_1_1ServerService.html", null ],
        [ "ServerTCPConnection", "classKargono_1_1Network_1_1ServerTCPConnection.html", "classKargono_1_1Network_1_1ServerTCPConnection" ],
        [ "ServerUDPConnection", "classKargono_1_1Network_1_1ServerUDPConnection.html", "classKargono_1_1Network_1_1ServerUDPConnection" ],
        [ "Session", "classKargono_1_1Network_1_1Session.html", "classKargono_1_1Network_1_1Session" ],
        [ "SessionInitCache", "structKargono_1_1Network_1_1SessionInitCache.html", "structKargono_1_1Network_1_1SessionInitCache" ],
        [ "TCPConnection", "classKargono_1_1Network_1_1TCPConnection.html", "classKargono_1_1Network_1_1TCPConnection" ],
        [ "UDPConnection", "classKargono_1_1Network_1_1UDPConnection.html", "classKargono_1_1Network_1_1UDPConnection" ]
      ] ],
      [ "Panels", "namespaceKargono_1_1Panels.html", [
        [ "AIStateEditorPanel", "classKargono_1_1Panels_1_1AIStateEditorPanel.html", "classKargono_1_1Panels_1_1AIStateEditorPanel" ],
        [ "AssetViewerPanel", "classKargono_1_1Panels_1_1AssetViewerPanel.html", "classKargono_1_1Panels_1_1AssetViewerPanel" ],
        [ "ContentBrowserPanel", "classKargono_1_1Panels_1_1ContentBrowserPanel.html", "classKargono_1_1Panels_1_1ContentBrowserPanel" ],
        [ "CreateWidgets", "structKargono_1_1Panels_1_1CreateWidgets.html", "structKargono_1_1Panels_1_1CreateWidgets" ],
        [ "DebugLine", "structKargono_1_1Panels_1_1DebugLine.html", "structKargono_1_1Panels_1_1DebugLine" ],
        [ "DebugPoint", "structKargono_1_1Panels_1_1DebugPoint.html", "structKargono_1_1Panels_1_1DebugPoint" ],
        [ "Document", "structKargono_1_1Panels_1_1Document.html", "structKargono_1_1Panels_1_1Document" ],
        [ "EditWidgets", "structKargono_1_1Panels_1_1EditWidgets.html", "structKargono_1_1Panels_1_1EditWidgets" ],
        [ "EmitterConfigPropertiesPanel", "classKargono_1_1Panels_1_1EmitterConfigPropertiesPanel.html", "classKargono_1_1Panels_1_1EmitterConfigPropertiesPanel" ],
        [ "EmitterConfigViewportPanel", "classKargono_1_1Panels_1_1EmitterConfigViewportPanel.html", "classKargono_1_1Panels_1_1EmitterConfigViewportPanel" ],
        [ "GameStatePanel", "classKargono_1_1Panels_1_1GameStatePanel.html", "classKargono_1_1Panels_1_1GameStatePanel" ],
        [ "ImGuiLog", "structKargono_1_1Panels_1_1ImGuiLog.html", "structKargono_1_1Panels_1_1ImGuiLog" ],
        [ "InputMapPanel", "classKargono_1_1Panels_1_1InputMapPanel.html", "classKargono_1_1Panels_1_1InputMapPanel" ],
        [ "LogPanel", "classKargono_1_1Panels_1_1LogPanel.html", "classKargono_1_1Panels_1_1LogPanel" ],
        [ "ProjectComponentPanel", "classKargono_1_1Panels_1_1ProjectComponentPanel.html", "classKargono_1_1Panels_1_1ProjectComponentPanel" ],
        [ "ProjectComponentWidgetData", "structKargono_1_1Panels_1_1ProjectComponentWidgetData.html", "structKargono_1_1Panels_1_1ProjectComponentWidgetData" ],
        [ "ProjectPanel", "classKargono_1_1Panels_1_1ProjectPanel.html", "classKargono_1_1Panels_1_1ProjectPanel" ],
        [ "PropertiesPanel", "classKargono_1_1Panels_1_1PropertiesPanel.html", "classKargono_1_1Panels_1_1PropertiesPanel" ],
        [ "SceneEditorPanel", "classKargono_1_1Panels_1_1SceneEditorPanel.html", "classKargono_1_1Panels_1_1SceneEditorPanel" ],
        [ "SceneEditorTreeEntryData", "structKargono_1_1Panels_1_1SceneEditorTreeEntryData.html", "structKargono_1_1Panels_1_1SceneEditorTreeEntryData" ],
        [ "ScriptEditorPanel", "classKargono_1_1Panels_1_1ScriptEditorPanel.html", "classKargono_1_1Panels_1_1ScriptEditorPanel" ],
        [ "StatisticsPanel", "classKargono_1_1Panels_1_1StatisticsPanel.html", "classKargono_1_1Panels_1_1StatisticsPanel" ],
        [ "TestingPanel", "classKargono_1_1Panels_1_1TestingPanel.html", "classKargono_1_1Panels_1_1TestingPanel" ],
        [ "TextEditorPanel", "classKargono_1_1Panels_1_1TextEditorPanel.html", "classKargono_1_1Panels_1_1TextEditorPanel" ],
        [ "UIEditorPropertiesPanel", "classKargono_1_1Panels_1_1UIEditorPropertiesPanel.html", "classKargono_1_1Panels_1_1UIEditorPropertiesPanel" ],
        [ "UIEditorTreePanel", "classKargono_1_1Panels_1_1UIEditorTreePanel.html", "classKargono_1_1Panels_1_1UIEditorTreePanel" ],
        [ "UIEditorViewportPanel", "classKargono_1_1Panels_1_1UIEditorViewportPanel.html", "classKargono_1_1Panels_1_1UIEditorViewportPanel" ],
        [ "ViewportPanel", "classKargono_1_1Panels_1_1ViewportPanel.html", "classKargono_1_1Panels_1_1ViewportPanel" ]
      ] ],
      [ "Particles", "namespaceKargono_1_1Particles.html", [
        [ "EmitterConfig", "structKargono_1_1Particles_1_1EmitterConfig.html", "structKargono_1_1Particles_1_1EmitterConfig" ],
        [ "EmitterInstance", "structKargono_1_1Particles_1_1EmitterInstance.html", "structKargono_1_1Particles_1_1EmitterInstance" ],
        [ "Particle", "structKargono_1_1Particles_1_1Particle.html", "structKargono_1_1Particles_1_1Particle" ],
        [ "ParticleService", "classKargono_1_1Particles_1_1ParticleService.html", null ]
      ] ],
      [ "Physics", "namespaceKargono_1_1Physics.html", [
        [ "ContactListener", "classKargono_1_1Physics_1_1ContactListener.html", "classKargono_1_1Physics_1_1ContactListener" ],
        [ "Physics2DService", "classKargono_1_1Physics_1_1Physics2DService.html", null ],
        [ "Physics2DWorld", "classKargono_1_1Physics_1_1Physics2DWorld.html", "classKargono_1_1Physics_1_1Physics2DWorld" ],
        [ "PhysicsSpecification", "structKargono_1_1Physics_1_1PhysicsSpecification.html", "structKargono_1_1Physics_1_1PhysicsSpecification" ],
        [ "RayCastCallback", "classKargono_1_1Physics_1_1RayCastCallback.html", "classKargono_1_1Physics_1_1RayCastCallback" ],
        [ "RaycastResult", "structKargono_1_1Physics_1_1RaycastResult.html", "structKargono_1_1Physics_1_1RaycastResult" ]
      ] ],
      [ "Projects", "namespaceKargono_1_1Projects.html", [
        [ "Project", "classKargono_1_1Projects_1_1Project.html", "classKargono_1_1Projects_1_1Project" ],
        [ "ProjectService", "classKargono_1_1Projects_1_1ProjectService.html", null ]
      ] ],
      [ "Rendering", "namespaceKargono_1_1Rendering.html", [
        [ "Camera", "classKargono_1_1Rendering_1_1Camera.html", "classKargono_1_1Rendering_1_1Camera" ],
        [ "DrawCallBuffer", "structKargono_1_1Rendering_1_1DrawCallBuffer.html", "structKargono_1_1Rendering_1_1DrawCallBuffer" ],
        [ "EditorOrthographicCamera", "classKargono_1_1Rendering_1_1EditorOrthographicCamera.html", "classKargono_1_1Rendering_1_1EditorOrthographicCamera" ],
        [ "EditorPerspectiveCamera", "classKargono_1_1Rendering_1_1EditorPerspectiveCamera.html", "classKargono_1_1Rendering_1_1EditorPerspectiveCamera" ],
        [ "Framebuffer", "classKargono_1_1Rendering_1_1Framebuffer.html", "classKargono_1_1Rendering_1_1Framebuffer" ],
        [ "FramebufferAttachmentSpecification", "structKargono_1_1Rendering_1_1FramebufferAttachmentSpecification.html", "structKargono_1_1Rendering_1_1FramebufferAttachmentSpecification" ],
        [ "FramebufferDataSpecification", "structKargono_1_1Rendering_1_1FramebufferDataSpecification.html", "structKargono_1_1Rendering_1_1FramebufferDataSpecification" ],
        [ "FramebufferSpecification", "structKargono_1_1Rendering_1_1FramebufferSpecification.html", "structKargono_1_1Rendering_1_1FramebufferSpecification" ],
        [ "IndexBuffer", "classKargono_1_1Rendering_1_1IndexBuffer.html", "classKargono_1_1Rendering_1_1IndexBuffer" ],
        [ "InputBufferElement", "structKargono_1_1Rendering_1_1InputBufferElement.html", "structKargono_1_1Rendering_1_1InputBufferElement" ],
        [ "InputBufferLayout", "classKargono_1_1Rendering_1_1InputBufferLayout.html", "classKargono_1_1Rendering_1_1InputBufferLayout" ],
        [ "RendererAPI", "classKargono_1_1Rendering_1_1RendererAPI.html", null ],
        [ "RendererInputSpec", "structKargono_1_1Rendering_1_1RendererInputSpec.html", "structKargono_1_1Rendering_1_1RendererInputSpec" ],
        [ "RenderingService", "classKargono_1_1Rendering_1_1RenderingService.html", "classKargono_1_1Rendering_1_1RenderingService" ],
        [ "Shader", "classKargono_1_1Rendering_1_1Shader.html", "classKargono_1_1Rendering_1_1Shader" ],
        [ "ShaderBuilder", "classKargono_1_1Rendering_1_1ShaderBuilder.html", null ],
        [ "ShaderSpecification", "structKargono_1_1Rendering_1_1ShaderSpecification.html", "structKargono_1_1Rendering_1_1ShaderSpecification" ],
        [ "Shape", "classKargono_1_1Rendering_1_1Shape.html", "classKargono_1_1Rendering_1_1Shape" ],
        [ "Texture", "classKargono_1_1Rendering_1_1Texture.html", "classKargono_1_1Rendering_1_1Texture" ],
        [ "Texture2D", "classKargono_1_1Rendering_1_1Texture2D.html", null ],
        [ "TextureSpecification", "structKargono_1_1Rendering_1_1TextureSpecification.html", "structKargono_1_1Rendering_1_1TextureSpecification" ],
        [ "UniformBuffer", "classKargono_1_1Rendering_1_1UniformBuffer.html", "classKargono_1_1Rendering_1_1UniformBuffer" ],
        [ "UniformBufferList", "classKargono_1_1Rendering_1_1UniformBufferList.html", "classKargono_1_1Rendering_1_1UniformBufferList" ],
        [ "UniformElement", "structKargono_1_1Rendering_1_1UniformElement.html", "structKargono_1_1Rendering_1_1UniformElement" ],
        [ "VertexArray", "classKargono_1_1Rendering_1_1VertexArray.html", "classKargono_1_1Rendering_1_1VertexArray" ],
        [ "VertexBuffer", "classKargono_1_1Rendering_1_1VertexBuffer.html", "classKargono_1_1Rendering_1_1VertexBuffer" ]
      ] ],
      [ "RuntimeUI", "namespaceKargono_1_1RuntimeUI.html", [
        [ "ButtonWidget", "classKargono_1_1RuntimeUI_1_1ButtonWidget.html", "classKargono_1_1RuntimeUI_1_1ButtonWidget" ],
        [ "Character", "structKargono_1_1RuntimeUI_1_1Character.html", "structKargono_1_1RuntimeUI_1_1Character" ],
        [ "CheckboxWidget", "classKargono_1_1RuntimeUI_1_1CheckboxWidget.html", "classKargono_1_1RuntimeUI_1_1CheckboxWidget" ],
        [ "DropDownWidget", "classKargono_1_1RuntimeUI_1_1DropDownWidget.html", "classKargono_1_1RuntimeUI_1_1DropDownWidget" ],
        [ "Font", "classKargono_1_1RuntimeUI_1_1Font.html", "classKargono_1_1RuntimeUI_1_1Font" ],
        [ "FontService", "classKargono_1_1RuntimeUI_1_1FontService.html", null ],
        [ "ImageButtonWidget", "classKargono_1_1RuntimeUI_1_1ImageButtonWidget.html", "classKargono_1_1RuntimeUI_1_1ImageButtonWidget" ],
        [ "ImageData", "structKargono_1_1RuntimeUI_1_1ImageData.html", "structKargono_1_1RuntimeUI_1_1ImageData" ],
        [ "ImageWidget", "classKargono_1_1RuntimeUI_1_1ImageWidget.html", "classKargono_1_1RuntimeUI_1_1ImageWidget" ],
        [ "InputTextWidget", "classKargono_1_1RuntimeUI_1_1InputTextWidget.html", "classKargono_1_1RuntimeUI_1_1InputTextWidget" ],
        [ "MultiLineTextData", "structKargono_1_1RuntimeUI_1_1MultiLineTextData.html", "structKargono_1_1RuntimeUI_1_1MultiLineTextData" ],
        [ "MultiLineTextDimensions", "structKargono_1_1RuntimeUI_1_1MultiLineTextDimensions.html", "structKargono_1_1RuntimeUI_1_1MultiLineTextDimensions" ],
        [ "NavigationLinks", "structKargono_1_1RuntimeUI_1_1NavigationLinks.html", "structKargono_1_1RuntimeUI_1_1NavigationLinks" ],
        [ "PopupWidget", "classKargono_1_1RuntimeUI_1_1PopupWidget.html", "classKargono_1_1RuntimeUI_1_1PopupWidget" ],
        [ "RuntimeUIService", "classKargono_1_1RuntimeUI_1_1RuntimeUIService.html", "classKargono_1_1RuntimeUI_1_1RuntimeUIService" ],
        [ "SelectionData", "structKargono_1_1RuntimeUI_1_1SelectionData.html", "structKargono_1_1RuntimeUI_1_1SelectionData" ],
        [ "SingleLineTextData", "structKargono_1_1RuntimeUI_1_1SingleLineTextData.html", "structKargono_1_1RuntimeUI_1_1SingleLineTextData" ],
        [ "SliderWidget", "classKargono_1_1RuntimeUI_1_1SliderWidget.html", "classKargono_1_1RuntimeUI_1_1SliderWidget" ],
        [ "TextWidget", "classKargono_1_1RuntimeUI_1_1TextWidget.html", "classKargono_1_1RuntimeUI_1_1TextWidget" ],
        [ "UserInterface", "classKargono_1_1RuntimeUI_1_1UserInterface.html", "classKargono_1_1RuntimeUI_1_1UserInterface" ],
        [ "UserInterfaceCallbacks", "structKargono_1_1RuntimeUI_1_1UserInterfaceCallbacks.html", "structKargono_1_1RuntimeUI_1_1UserInterfaceCallbacks" ],
        [ "Widget", "classKargono_1_1RuntimeUI_1_1Widget.html", "classKargono_1_1RuntimeUI_1_1Widget" ],
        [ "WidgetCallbacks", "structKargono_1_1RuntimeUI_1_1WidgetCallbacks.html", "structKargono_1_1RuntimeUI_1_1WidgetCallbacks" ],
        [ "WidgetID", "structKargono_1_1RuntimeUI_1_1WidgetID.html", "structKargono_1_1RuntimeUI_1_1WidgetID" ],
        [ "Window", "classKargono_1_1RuntimeUI_1_1Window.html", "classKargono_1_1RuntimeUI_1_1Window" ],
        [ "WindowID", "structKargono_1_1RuntimeUI_1_1WindowID.html", "structKargono_1_1RuntimeUI_1_1WindowID" ]
      ] ],
      [ "Scenes", "namespaceKargono_1_1Scenes.html", [
        [ "GameState", "classKargono_1_1Scenes_1_1GameState.html", "classKargono_1_1Scenes_1_1GameState" ],
        [ "GameStateService", "classKargono_1_1Scenes_1_1GameStateService.html", null ],
        [ "Scene", "classKargono_1_1Scenes_1_1Scene.html", "classKargono_1_1Scenes_1_1Scene" ],
        [ "SceneCamera", "classKargono_1_1Scenes_1_1SceneCamera.html", "classKargono_1_1Scenes_1_1SceneCamera" ],
        [ "SceneService", "classKargono_1_1Scenes_1_1SceneService.html", null ]
      ] ],
      [ "Scripting", "namespaceKargono_1_1Scripting.html", [
        [ "BinaryOperationNode", "structKargono_1_1Scripting_1_1BinaryOperationNode.html", "structKargono_1_1Scripting_1_1BinaryOperationNode" ],
        [ "CursorContext", "structKargono_1_1Scripting_1_1CursorContext.html", "structKargono_1_1Scripting_1_1CursorContext" ],
        [ "CustomLiteralInfo", "structKargono_1_1Scripting_1_1CustomLiteralInfo.html", "structKargono_1_1Scripting_1_1CustomLiteralInfo" ],
        [ "CustomLiteralMember", "structKargono_1_1Scripting_1_1CustomLiteralMember.html", "structKargono_1_1Scripting_1_1CustomLiteralMember" ],
        [ "CustomLiteralNode", "structKargono_1_1Scripting_1_1CustomLiteralNode.html", "structKargono_1_1Scripting_1_1CustomLiteralNode" ],
        [ "DataMember", "structKargono_1_1Scripting_1_1DataMember.html", "structKargono_1_1Scripting_1_1DataMember" ],
        [ "ExplicitFuncType", "structKargono_1_1Scripting_1_1ExplicitFuncType.html", "structKargono_1_1Scripting_1_1ExplicitFuncType" ],
        [ "Expression", "structKargono_1_1Scripting_1_1Expression.html", "structKargono_1_1Scripting_1_1Expression" ],
        [ "ExpressionGenerationAffixes", "structKargono_1_1Scripting_1_1ExpressionGenerationAffixes.html", "structKargono_1_1Scripting_1_1ExpressionGenerationAffixes" ],
        [ "FunctionCallNode", "structKargono_1_1Scripting_1_1FunctionCallNode.html", "structKargono_1_1Scripting_1_1FunctionCallNode" ],
        [ "FunctionNode", "structKargono_1_1Scripting_1_1FunctionNode.html", "structKargono_1_1Scripting_1_1FunctionNode" ],
        [ "FunctionParameter", "structKargono_1_1Scripting_1_1FunctionParameter.html", "structKargono_1_1Scripting_1_1FunctionParameter" ],
        [ "InitializationListNode", "structKargono_1_1Scripting_1_1InitializationListNode.html", "structKargono_1_1Scripting_1_1InitializationListNode" ],
        [ "InitializationListType", "structKargono_1_1Scripting_1_1InitializationListType.html", "structKargono_1_1Scripting_1_1InitializationListType" ],
        [ "LanguageDefinition", "structKargono_1_1Scripting_1_1LanguageDefinition.html", "structKargono_1_1Scripting_1_1LanguageDefinition" ],
        [ "MemberNode", "structKargono_1_1Scripting_1_1MemberNode.html", "structKargono_1_1Scripting_1_1MemberNode" ],
        [ "MemberType", "structKargono_1_1Scripting_1_1MemberType.html", "structKargono_1_1Scripting_1_1MemberType" ],
        [ "ParserError", "structKargono_1_1Scripting_1_1ParserError.html", "structKargono_1_1Scripting_1_1ParserError" ],
        [ "PrimitiveType", "structKargono_1_1Scripting_1_1PrimitiveType.html", "structKargono_1_1Scripting_1_1PrimitiveType" ],
        [ "ProgramNode", "structKargono_1_1Scripting_1_1ProgramNode.html", "structKargono_1_1Scripting_1_1ProgramNode" ],
        [ "Script", "classKargono_1_1Scripting_1_1Script.html", "classKargono_1_1Scripting_1_1Script" ],
        [ "ScriptAST", "structKargono_1_1Scripting_1_1ScriptAST.html", "structKargono_1_1Scripting_1_1ScriptAST" ],
        [ "ScriptCompilerService", "classKargono_1_1Scripting_1_1ScriptCompilerService.html", null ],
        [ "ScriptModuleBuilder", "classKargono_1_1Scripting_1_1ScriptModuleBuilder.html", "classKargono_1_1Scripting_1_1ScriptModuleBuilder" ],
        [ "ScriptOutputGenerator", "classKargono_1_1Scripting_1_1ScriptOutputGenerator.html", "classKargono_1_1Scripting_1_1ScriptOutputGenerator" ],
        [ "ScriptService", "classKargono_1_1Scripting_1_1ScriptService.html", null ],
        [ "ScriptToken", "structKargono_1_1Scripting_1_1ScriptToken.html", "structKargono_1_1Scripting_1_1ScriptToken" ],
        [ "ScriptTokenizer", "classKargono_1_1Scripting_1_1ScriptTokenizer.html", "classKargono_1_1Scripting_1_1ScriptTokenizer" ],
        [ "ScriptTokenParser", "classKargono_1_1Scripting_1_1ScriptTokenParser.html", "classKargono_1_1Scripting_1_1ScriptTokenParser" ],
        [ "StackVariable", "structKargono_1_1Scripting_1_1StackVariable.html", "structKargono_1_1Scripting_1_1StackVariable" ],
        [ "Statement", "structKargono_1_1Scripting_1_1Statement.html", "structKargono_1_1Scripting_1_1Statement" ],
        [ "StatementAssignment", "structKargono_1_1Scripting_1_1StatementAssignment.html", "structKargono_1_1Scripting_1_1StatementAssignment" ],
        [ "StatementBreak", "structKargono_1_1Scripting_1_1StatementBreak.html", null ],
        [ "StatementConditional", "structKargono_1_1Scripting_1_1StatementConditional.html", "structKargono_1_1Scripting_1_1StatementConditional" ],
        [ "StatementContinue", "structKargono_1_1Scripting_1_1StatementContinue.html", null ],
        [ "StatementDeclaration", "structKargono_1_1Scripting_1_1StatementDeclaration.html", "structKargono_1_1Scripting_1_1StatementDeclaration" ],
        [ "StatementDeclarationAssignment", "structKargono_1_1Scripting_1_1StatementDeclarationAssignment.html", "structKargono_1_1Scripting_1_1StatementDeclarationAssignment" ],
        [ "StatementEmpty", "structKargono_1_1Scripting_1_1StatementEmpty.html", null ],
        [ "StatementExpression", "structKargono_1_1Scripting_1_1StatementExpression.html", "structKargono_1_1Scripting_1_1StatementExpression" ],
        [ "StatementReturn", "structKargono_1_1Scripting_1_1StatementReturn.html", "structKargono_1_1Scripting_1_1StatementReturn" ],
        [ "StatementWhileLoop", "structKargono_1_1Scripting_1_1StatementWhileLoop.html", "structKargono_1_1Scripting_1_1StatementWhileLoop" ],
        [ "SuggestionSpec", "structKargono_1_1Scripting_1_1SuggestionSpec.html", "structKargono_1_1Scripting_1_1SuggestionSpec" ],
        [ "TernaryOperationNode", "structKargono_1_1Scripting_1_1TernaryOperationNode.html", "structKargono_1_1Scripting_1_1TernaryOperationNode" ],
        [ "TokenExpressionNode", "structKargono_1_1Scripting_1_1TokenExpressionNode.html", "structKargono_1_1Scripting_1_1TokenExpressionNode" ],
        [ "UnaryOperationNode", "structKargono_1_1Scripting_1_1UnaryOperationNode.html", "structKargono_1_1Scripting_1_1UnaryOperationNode" ]
      ] ],
      [ "Utility", "namespaceKargono_1_1Utility.html", [
        [ "AsyncBusyTimer", "classKargono_1_1Utility_1_1AsyncBusyTimer.html", "classKargono_1_1Utility_1_1AsyncBusyTimer" ],
        [ "Conversions", "classKargono_1_1Utility_1_1Conversions.html", "classKargono_1_1Utility_1_1Conversions" ],
        [ "FileDialogs", "classKargono_1_1Utility_1_1FileDialogs.html", null ],
        [ "FileSystem", "classKargono_1_1Utility_1_1FileSystem.html", null ],
        [ "Operations", "classKargono_1_1Utility_1_1Operations.html", null ],
        [ "OSCommands", "classKargono_1_1Utility_1_1OSCommands.html", null ],
        [ "PassiveTimer", "classKargono_1_1Utility_1_1PassiveTimer.html", "classKargono_1_1Utility_1_1PassiveTimer" ],
        [ "PseudoGenerator", "classKargono_1_1Utility_1_1PseudoGenerator.html", "classKargono_1_1Utility_1_1PseudoGenerator" ],
        [ "PseudoRandomService", "classKargono_1_1Utility_1_1PseudoRandomService.html", null ],
        [ "RandomService", "classKargono_1_1Utility_1_1RandomService.html", null ],
        [ "Regex", "classKargono_1_1Utility_1_1Regex.html", null ],
        [ "ScopedTimer", "classKargono_1_1Utility_1_1ScopedTimer.html", "classKargono_1_1Utility_1_1ScopedTimer" ],
        [ "Time", "classKargono_1_1Utility_1_1Time.html", null ]
      ] ],
      [ "Windows", "namespaceKargono_1_1Windows.html", [
        [ "EmitterConfigWindow", "classKargono_1_1Windows_1_1EmitterConfigWindow.html", "classKargono_1_1Windows_1_1EmitterConfigWindow" ],
        [ "MainWindow", "classKargono_1_1Windows_1_1MainWindow.html", "classKargono_1_1Windows_1_1MainWindow" ],
        [ "UIEditorWindow", "classKargono_1_1Windows_1_1UIEditorWindow.html", "classKargono_1_1Windows_1_1UIEditorWindow" ]
      ] ],
      [ "Application", "classKargono_1_1Application.html", "classKargono_1_1Application" ],
      [ "AppTickGenerator", "structKargono_1_1AppTickGenerator.html", "structKargono_1_1AppTickGenerator" ],
      [ "AppTickService", "classKargono_1_1AppTickService.html", null ],
      [ "BitField", "classKargono_1_1BitField.html", "classKargono_1_1BitField" ],
      [ "Buffer", "structKargono_1_1Buffer.html", "structKargono_1_1Buffer" ],
      [ "CommandLineArguments", "structKargono_1_1CommandLineArguments.html", "structKargono_1_1CommandLineArguments" ],
      [ "EditorApp", "classKargono_1_1EditorApp.html", "classKargono_1_1EditorApp" ],
      [ "Engine", "classKargono_1_1Engine.html", "classKargono_1_1Engine" ],
      [ "EngineService", "classKargono_1_1EngineService.html", null ],
      [ "EngineSpec", "structKargono_1_1EngineSpec.html", "structKargono_1_1EngineSpec" ],
      [ "FixedString", "classKargono_1_1FixedString.html", "classKargono_1_1FixedString" ],
      [ "LauncherApp", "classKargono_1_1LauncherApp.html", "classKargono_1_1LauncherApp" ],
      [ "Log", "classKargono_1_1Log.html", null ],
      [ "RuntimeApp", "classKargono_1_1RuntimeApp.html", "classKargono_1_1RuntimeApp" ],
      [ "ServerApp", "classKargono_1_1ServerApp.html", "classKargono_1_1ServerApp" ],
      [ "Timestep", "classKargono_1_1Timestep.html", "classKargono_1_1Timestep" ],
      [ "TSQueue", "classKargono_1_1TSQueue.html", "classKargono_1_1TSQueue" ],
      [ "UUID", "classKargono_1_1UUID.html", "classKargono_1_1UUID" ],
      [ "ViewportData", "structKargono_1_1ViewportData.html", "structKargono_1_1ViewportData" ],
      [ "Window", "classKargono_1_1Window.html", "classKargono_1_1Window" ],
      [ "WindowProps", "structKargono_1_1WindowProps.html", "structKargono_1_1WindowProps" ],
      [ "WrappedBool", "classKargono_1_1WrappedBool.html", "classKargono_1_1WrappedBool" ],
      [ "WrappedBoolEntity", "classKargono_1_1WrappedBoolEntity.html", "classKargono_1_1WrappedBoolEntity" ],
      [ "WrappedBoolEntityEntity", "classKargono_1_1WrappedBoolEntityEntity.html", "classKargono_1_1WrappedBoolEntityEntity" ],
      [ "WrappedBoolNone", "classKargono_1_1WrappedBoolNone.html", "classKargono_1_1WrappedBoolNone" ],
      [ "WrappedEntity", "classKargono_1_1WrappedEntity.html", "classKargono_1_1WrappedEntity" ],
      [ "WrappedFloat", "classKargono_1_1WrappedFloat.html", "classKargono_1_1WrappedFloat" ],
      [ "WrappedFunction", "classKargono_1_1WrappedFunction.html", "classKargono_1_1WrappedFunction" ],
      [ "WrappedInteger32", "classKargono_1_1WrappedInteger32.html", "classKargono_1_1WrappedInteger32" ],
      [ "WrappedString", "classKargono_1_1WrappedString.html", "classKargono_1_1WrappedString" ],
      [ "WrappedUInteger16", "classKargono_1_1WrappedUInteger16.html", "classKargono_1_1WrappedUInteger16" ],
      [ "WrappedUInteger32", "classKargono_1_1WrappedUInteger32.html", "classKargono_1_1WrappedUInteger32" ],
      [ "WrappedUInteger64", "classKargono_1_1WrappedUInteger64.html", "classKargono_1_1WrappedUInteger64" ],
      [ "WrappedVariable", "classKargono_1_1WrappedVariable.html", "classKargono_1_1WrappedVariable" ],
      [ "WrappedVector3", "classKargono_1_1WrappedVector3.html", "classKargono_1_1WrappedVector3" ],
      [ "WrappedVoidBool", "classKargono_1_1WrappedVoidBool.html", "classKargono_1_1WrappedVoidBool" ],
      [ "WrappedVoidEntity", "classKargono_1_1WrappedVoidEntity.html", "classKargono_1_1WrappedVoidEntity" ],
      [ "WrappedVoidEntityFloat", "classKargono_1_1WrappedVoidEntityFloat.html", "classKargono_1_1WrappedVoidEntityFloat" ],
      [ "WrappedVoidFloat", "classKargono_1_1WrappedVoidFloat.html", "classKargono_1_1WrappedVoidFloat" ],
      [ "WrappedVoidNone", "classKargono_1_1WrappedVoidNone.html", "classKargono_1_1WrappedVoidNone" ],
      [ "WrappedVoidString", "classKargono_1_1WrappedVoidString.html", "classKargono_1_1WrappedVoidString" ],
      [ "WrappedVoidUInt16", "classKargono_1_1WrappedVoidUInt16.html", "classKargono_1_1WrappedVoidUInt16" ],
      [ "WrappedVoidUInt32", "classKargono_1_1WrappedVoidUInt32.html", "classKargono_1_1WrappedVoidUInt32" ],
      [ "WrappedVoidUInt32EntityEntityFloat", "classKargono_1_1WrappedVoidUInt32EntityEntityFloat.html", "classKargono_1_1WrappedVoidUInt32EntityEntityFloat" ],
      [ "WrappedVoidUInt32UInt32", "classKargono_1_1WrappedVoidUInt32UInt32.html", "classKargono_1_1WrappedVoidUInt32UInt32" ]
    ] ],
    [ "YAML", "namespaceYAML.html", [
      [ "convert< Kargono::Math::ivec2 >", "structYAML_1_1convert_3_01Kargono_1_1Math_1_1ivec2_01_4.html", null ],
      [ "convert< Kargono::Math::ivec3 >", "structYAML_1_1convert_3_01Kargono_1_1Math_1_1ivec3_01_4.html", null ],
      [ "convert< Kargono::Math::ivec4 >", "structYAML_1_1convert_3_01Kargono_1_1Math_1_1ivec4_01_4.html", null ],
      [ "convert< Kargono::Math::vec2 >", "structYAML_1_1convert_3_01Kargono_1_1Math_1_1vec2_01_4.html", null ],
      [ "convert< Kargono::Math::vec3 >", "structYAML_1_1convert_3_01Kargono_1_1Math_1_1vec3_01_4.html", null ],
      [ "convert< Kargono::Math::vec4 >", "structYAML_1_1convert_3_01Kargono_1_1Math_1_1vec4_01_4.html", null ],
      [ "convert< Kargono::UUID >", "structYAML_1_1convert_3_01Kargono_1_1UUID_01_4.html", null ]
    ] ]
];