var hierarchy =
[
    [ "Kargono::Application", "classKargono_1_1Application.html", [
      [ "Kargono::EditorApp", "classKargono_1_1EditorApp.html", null ],
      [ "Kargono::RuntimeApp", "classKargono_1_1RuntimeApp.html", null ],
      [ "Kargono::ServerApp", "classKargono_1_1ServerApp.html", null ]
    ] ],
    [ "Kargono::AppSpec", "structKargono_1_1AppSpec.html", null ],
    [ "Kargono::AppTickEngine", "classKargono_1_1AppTickEngine.html", null ],
    [ "Kargono::AppTickGenerator", "structKargono_1_1AppTickGenerator.html", null ],
    [ "Kargono::Assets::Asset", "structKargono_1_1Assets_1_1Asset.html", null ],
    [ "Kargono::Assets::AssetManager", "classKargono_1_1Assets_1_1AssetManager.html", null ],
    [ "Kargono::Timers::AsyncBusyTimer", "classKargono_1_1Timers_1_1AsyncBusyTimer.html", null ],
    [ "Kargono::Audio::AudioBuffer", "classKargono_1_1Audio_1_1AudioBuffer.html", null ],
    [ "Kargono::AudioComponent", "structKargono_1_1AudioComponent.html", null ],
    [ "Kargono::Audio::AudioEngine", "classKargono_1_1Audio_1_1AudioEngine.html", null ],
    [ "Kargono::Audio::AudioListener", "classKargono_1_1Audio_1_1AudioListener.html", null ],
    [ "Kargono::Audio::AudioListenerSpecification", "structKargono_1_1Audio_1_1AudioListenerSpecification.html", null ],
    [ "Kargono::Assets::AudioMetaData", "structKargono_1_1Assets_1_1AudioMetaData.html", null ],
    [ "Kargono::Audio::AudioSource", "classKargono_1_1Audio_1_1AudioSource.html", null ],
    [ "Kargono::Audio::AudioSourceSpecification", "structKargono_1_1Audio_1_1AudioSourceSpecification.html", null ],
    [ "b2ContactListener", null, [
      [ "Kargono::Physics::ContactListener", "classKargono_1_1Physics_1_1ContactListener.html", null ]
    ] ],
    [ "Kargono::BoxCollider2DComponent", "structKargono_1_1BoxCollider2DComponent.html", null ],
    [ "Kargono::Buffer", "structKargono_1_1Buffer.html", null ],
    [ "Kargono::Camera", "classKargono_1_1Camera.html", [
      [ "Kargono::EditorCamera", "classKargono_1_1EditorCamera.html", null ],
      [ "Kargono::SceneCamera", "classKargono_1_1SceneCamera.html", null ]
    ] ],
    [ "Kargono::CameraComponent", "structKargono_1_1CameraComponent.html", null ],
    [ "Kargono::RuntimeUI::Character", "structKargono_1_1RuntimeUI_1_1Character.html", null ],
    [ "Kargono::EditorUI::CheckboxSpec", "structKargono_1_1EditorUI_1_1CheckboxSpec.html", null ],
    [ "Kargono::CircleCollider2DComponent", "structKargono_1_1CircleCollider2DComponent.html", null ],
    [ "Kargono::ClassField", "structKargono_1_1ClassField.html", null ],
    [ "Kargono::ClassInstanceComponent", "structKargono_1_1ClassInstanceComponent.html", null ],
    [ "Kargono::Network::ClientInterface", "classKargono_1_1Network_1_1ClientInterface.html", [
      [ "Kargono::Network::Client", "classKargono_1_1Network_1_1Client.html", null ]
    ] ],
    [ "Kargono::EditorUI::CollapsingHeaderSpec", "structKargono_1_1EditorUI_1_1CollapsingHeaderSpec.html", null ],
    [ "Kargono::CommandLineArgs", "structKargono_1_1CommandLineArgs.html", null ],
    [ "Kargono::ComponentGroup< Components >", "structKargono_1_1ComponentGroup.html", null ],
    [ "Kargono::Network::Connection", "classKargono_1_1Network_1_1Connection.html", [
      [ "Kargono::Network::ConnectionToClient", "classKargono_1_1Network_1_1ConnectionToClient.html", null ],
      [ "Kargono::Network::ConnectionToServer", "classKargono_1_1Network_1_1ConnectionToServer.html", null ]
    ] ],
    [ "Kargono::ContentBrowserPanel", "classKargono_1_1ContentBrowserPanel.html", null ],
    [ "Kargono::Utility::Conversions", "classKargono_1_1Utility_1_1Conversions.html", null ],
    [ "YAML::convert< Kargono::Math::ivec2 >", "structYAML_1_1convert_3_01Kargono_1_1Math_1_1ivec2_01_4.html", null ],
    [ "YAML::convert< Kargono::Math::ivec3 >", "structYAML_1_1convert_3_01Kargono_1_1Math_1_1ivec3_01_4.html", null ],
    [ "YAML::convert< Kargono::Math::ivec4 >", "structYAML_1_1convert_3_01Kargono_1_1Math_1_1ivec4_01_4.html", null ],
    [ "YAML::convert< Kargono::Math::vec2 >", "structYAML_1_1convert_3_01Kargono_1_1Math_1_1vec2_01_4.html", null ],
    [ "YAML::convert< Kargono::Math::vec3 >", "structYAML_1_1convert_3_01Kargono_1_1Math_1_1vec3_01_4.html", null ],
    [ "YAML::convert< Kargono::Math::vec4 >", "structYAML_1_1convert_3_01Kargono_1_1Math_1_1vec4_01_4.html", null ],
    [ "YAML::convert< Kargono::UUID >", "structYAML_1_1convert_3_01Kargono_1_1UUID_01_4.html", null ],
    [ "Kargono::RuntimeUI::DirectionPointers", "structKargono_1_1RuntimeUI_1_1DirectionPointers.html", null ],
    [ "Kargono::DrawCallBuffer", "structKargono_1_1DrawCallBuffer.html", null ],
    [ "Kargono::EditorUI::Editor", "classKargono_1_1EditorUI_1_1Editor.html", null ],
    [ "Kargono::EditorUI::EditVariableSpec", "structKargono_1_1EditorUI_1_1EditVariableSpec.html", null ],
    [ "std::enable_shared_from_this", null, [
      [ "Kargono::Network::ConnectionToClient", "classKargono_1_1Network_1_1ConnectionToClient.html", null ],
      [ "Kargono::Network::ConnectionToServer", "classKargono_1_1Network_1_1ConnectionToServer.html", null ],
      [ "Kargono::Network::UDPClient", "classKargono_1_1Network_1_1UDPClient.html", null ],
      [ "Kargono::Network::UDPServer", "classKargono_1_1Network_1_1UDPServer.html", null ]
    ] ],
    [ "Kargono::EngineCore", "classKargono_1_1EngineCore.html", null ],
    [ "Kargono::Entity", "classKargono_1_1Entity.html", null ],
    [ "Kargono::EntityClass", "classKargono_1_1EntityClass.html", null ],
    [ "Kargono::EntityClassEditor", "classKargono_1_1EntityClassEditor.html", null ],
    [ "Kargono::Assets::EntityClassMetaData", "structKargono_1_1Assets_1_1EntityClassMetaData.html", null ],
    [ "Kargono::EntityScripts", "structKargono_1_1EntityScripts.html", null ],
    [ "Kargono::Events::Event", "classKargono_1_1Events_1_1Event.html", [
      [ "Kargono::Events::AddExtraUpdateEvent", "classKargono_1_1Events_1_1AddExtraUpdateEvent.html", null ],
      [ "Kargono::Events::AddTickGeneratorUsage", "classKargono_1_1Events_1_1AddTickGeneratorUsage.html", null ],
      [ "Kargono::Events::AppTickEvent", "classKargono_1_1Events_1_1AppTickEvent.html", null ],
      [ "Kargono::Events::ApplicationCloseEvent", "classKargono_1_1Events_1_1ApplicationCloseEvent.html", null ],
      [ "Kargono::Events::ApproveJoinSession", "classKargono_1_1Events_1_1ApproveJoinSession.html", null ],
      [ "Kargono::Events::CleanUpTimersEvent", "classKargono_1_1Events_1_1CleanUpTimersEvent.html", null ],
      [ "Kargono::Events::ConnectionTerminated", "classKargono_1_1Events_1_1ConnectionTerminated.html", null ],
      [ "Kargono::Events::CurrentSessionInit", "classKargono_1_1Events_1_1CurrentSessionInit.html", null ],
      [ "Kargono::Events::DenyJoinSession", "classKargono_1_1Events_1_1DenyJoinSession.html", null ],
      [ "Kargono::Events::EnableReadyCheck", "classKargono_1_1Events_1_1EnableReadyCheck.html", null ],
      [ "Kargono::Events::KeyEvent", "classKargono_1_1Events_1_1KeyEvent.html", [
        [ "Kargono::Events::KeyPressedEvent", "classKargono_1_1Events_1_1KeyPressedEvent.html", null ],
        [ "Kargono::Events::KeyReleasedEvent", "classKargono_1_1Events_1_1KeyReleasedEvent.html", null ],
        [ "Kargono::Events::KeyTypedEvent", "classKargono_1_1Events_1_1KeyTypedEvent.html", null ]
      ] ],
      [ "Kargono::Events::LeaveCurrentSession", "classKargono_1_1Events_1_1LeaveCurrentSession.html", null ],
      [ "Kargono::Events::MouseButtonEvent", "classKargono_1_1Events_1_1MouseButtonEvent.html", [
        [ "Kargono::Events::MouseButtonPressedEvent", "classKargono_1_1Events_1_1MouseButtonPressedEvent.html", null ],
        [ "Kargono::Events::MouseButtonReleasedEvent", "classKargono_1_1Events_1_1MouseButtonReleasedEvent.html", null ]
      ] ],
      [ "Kargono::Events::MouseMovedEvent", "classKargono_1_1Events_1_1MouseMovedEvent.html", null ],
      [ "Kargono::Events::MouseScrolledEvent", "classKargono_1_1Events_1_1MouseScrolledEvent.html", null ],
      [ "Kargono::Events::PhysicsCollisionEnd", "classKargono_1_1Events_1_1PhysicsCollisionEnd.html", null ],
      [ "Kargono::Events::PhysicsCollisionEvent", "classKargono_1_1Events_1_1PhysicsCollisionEvent.html", null ],
      [ "Kargono::Events::ReceiveSignal", "classKargono_1_1Events_1_1ReceiveSignal.html", null ],
      [ "Kargono::Events::RemoveTickGeneratorUsage", "classKargono_1_1Events_1_1RemoveTickGeneratorUsage.html", null ],
      [ "Kargono::Events::RequestJoinSession", "classKargono_1_1Events_1_1RequestJoinSession.html", null ],
      [ "Kargono::Events::RequestUserCount", "classKargono_1_1Events_1_1RequestUserCount.html", null ],
      [ "Kargono::Events::SendAllEntityLocation", "classKargono_1_1Events_1_1SendAllEntityLocation.html", null ],
      [ "Kargono::Events::SendAllEntityPhysics", "classKargono_1_1Events_1_1SendAllEntityPhysics.html", null ],
      [ "Kargono::Events::SessionReadyCheck", "classKargono_1_1Events_1_1SessionReadyCheck.html", null ],
      [ "Kargono::Events::SessionReadyCheckConfirm", "classKargono_1_1Events_1_1SessionReadyCheckConfirm.html", null ],
      [ "Kargono::Events::SignalAll", "classKargono_1_1Events_1_1SignalAll.html", null ],
      [ "Kargono::Events::SkipUpdateEvent", "classKargono_1_1Events_1_1SkipUpdateEvent.html", null ],
      [ "Kargono::Events::StartSession", "classKargono_1_1Events_1_1StartSession.html", null ],
      [ "Kargono::Events::UpdateEntityLocation", "classKargono_1_1Events_1_1UpdateEntityLocation.html", null ],
      [ "Kargono::Events::UpdateEntityPhysics", "classKargono_1_1Events_1_1UpdateEntityPhysics.html", null ],
      [ "Kargono::Events::UpdateOnlineUsers", "classKargono_1_1Events_1_1UpdateOnlineUsers.html", null ],
      [ "Kargono::Events::UpdateSessionUserSlot", "classKargono_1_1Events_1_1UpdateSessionUserSlot.html", null ],
      [ "Kargono::Events::UserLeftSession", "classKargono_1_1Events_1_1UserLeftSession.html", null ],
      [ "Kargono::Events::WindowCloseEvent", "classKargono_1_1Events_1_1WindowCloseEvent.html", null ],
      [ "Kargono::Events::WindowResizeEvent", "classKargono_1_1Events_1_1WindowResizeEvent.html", null ]
    ] ],
    [ "Kargono::Events::EventDispatcher", "classKargono_1_1Events_1_1EventDispatcher.html", null ],
    [ "Kargono::Utility::FileDialogs", "classKargono_1_1Utility_1_1FileDialogs.html", null ],
    [ "Kargono::Utility::FileSystem", "classKargono_1_1Utility_1_1FileSystem.html", null ],
    [ "Kargono::RuntimeUI::Font", "classKargono_1_1RuntimeUI_1_1Font.html", null ],
    [ "Kargono::Assets::FontMetaData", "structKargono_1_1Assets_1_1FontMetaData.html", null ],
    [ "Kargono::Framebuffer", "classKargono_1_1Framebuffer.html", [
      [ "API::RenderingAPI::OpenGLFramebuffer", "classAPI_1_1RenderingAPI_1_1OpenGLFramebuffer.html", null ]
    ] ],
    [ "Kargono::FramebufferAttachmentSpecification", "structKargono_1_1FramebufferAttachmentSpecification.html", null ],
    [ "Kargono::FramebufferDataSpecification", "structKargono_1_1FramebufferDataSpecification.html", null ],
    [ "Kargono::FramebufferSpecification", "structKargono_1_1FramebufferSpecification.html", null ],
    [ "Kargono::GameState", "classKargono_1_1GameState.html", null ],
    [ "Kargono::Assets::GameStateMetaData", "structKargono_1_1Assets_1_1GameStateMetaData.html", null ],
    [ "Kargono::GameStatePanel", "classKargono_1_1GameStatePanel.html", null ],
    [ "Kargono::EditorUI::GenericPopupSpec", "structKargono_1_1EditorUI_1_1GenericPopupSpec.html", null ],
    [ "std::hash< Kargono::UUID >", "structstd_1_1hash_3_01Kargono_1_1UUID_01_4.html", null ],
    [ "Kargono::IDComponent", "structKargono_1_1IDComponent.html", null ],
    [ "Kargono::ImGuiLog", "structKargono_1_1ImGuiLog.html", null ],
    [ "Kargono::IndexBuffer", "classKargono_1_1IndexBuffer.html", [
      [ "API::RenderingAPI::OpenGLIndexBuffer", "classAPI_1_1RenderingAPI_1_1OpenGLIndexBuffer.html", null ]
    ] ],
    [ "Kargono::EditorUI::InlineButtonSpec", "structKargono_1_1EditorUI_1_1InlineButtonSpec.html", null ],
    [ "Kargono::InputMode::InputActionBinding", "classKargono_1_1InputMode_1_1InputActionBinding.html", [
      [ "Kargono::InputMode::KeyboardActionBinding", "classKargono_1_1InputMode_1_1KeyboardActionBinding.html", null ]
    ] ],
    [ "Kargono::InputBufferElement", "structKargono_1_1InputBufferElement.html", null ],
    [ "Kargono::InputBufferLayout", "classKargono_1_1InputBufferLayout.html", null ],
    [ "Kargono::InputEditorPanel", "classKargono_1_1InputEditorPanel.html", null ],
    [ "Kargono::InputMode", "classKargono_1_1InputMode.html", null ],
    [ "Kargono::Assets::InputModeMetaData", "structKargono_1_1Assets_1_1InputModeMetaData.html", null ],
    [ "Kargono::InputPolling", "classKargono_1_1InputPolling.html", null ],
    [ "Kargono::Network::LabeledMessage", "structKargono_1_1Network_1_1LabeledMessage.html", null ],
    [ "Kargono::Log", "classKargono_1_1Log.html", null ],
    [ "Kargono::LogPanel", "classKargono_1_1LogPanel.html", null ],
    [ "Kargono::Network::Message", "structKargono_1_1Network_1_1Message.html", null ],
    [ "Kargono::Network::MessageHeader", "structKargono_1_1Network_1_1MessageHeader.html", null ],
    [ "Kargono::Assets::Metadata", "structKargono_1_1Assets_1_1Metadata.html", null ],
    [ "Kargono::MultiAudioComponent", "structKargono_1_1MultiAudioComponent.html", null ],
    [ "Kargono::NetworkComponent", "structKargono_1_1NetworkComponent.html", null ],
    [ "Kargono::Utility::Operations", "classKargono_1_1Utility_1_1Operations.html", null ],
    [ "Kargono::EditorUI::OptionEntry", "structKargono_1_1EditorUI_1_1OptionEntry.html", null ],
    [ "Kargono::Utility::OSCommands", "classKargono_1_1Utility_1_1OSCommands.html", null ],
    [ "Kargono::Network::owned_message", "structKargono_1_1Network_1_1owned__message.html", null ],
    [ "Kargono::Physics::Physics2DWorld", "classKargono_1_1Physics_1_1Physics2DWorld.html", null ],
    [ "Kargono::Physics::PhysicsSpecification", "structKargono_1_1Physics_1_1PhysicsSpecification.html", null ],
    [ "Kargono::Projects::Project", "classKargono_1_1Projects_1_1Project.html", null ],
    [ "Kargono::Projects::ProjectConfig", "structKargono_1_1Projects_1_1ProjectConfig.html", null ],
    [ "Kargono::ProjectPanel", "classKargono_1_1ProjectPanel.html", null ],
    [ "Kargono::EditorUI::RadioSelectorSpec", "structKargono_1_1EditorUI_1_1RadioSelectorSpec.html", null ],
    [ "Kargono::Utility::Regex", "classKargono_1_1Utility_1_1Regex.html", null ],
    [ "Kargono::RenderCommand", "classKargono_1_1RenderCommand.html", null ],
    [ "Kargono::Renderer", "classKargono_1_1Renderer.html", null ],
    [ "Kargono::RendererAPI", "classKargono_1_1RendererAPI.html", [
      [ "API::RenderingAPI::OpenGLRendererAPI", "classAPI_1_1RenderingAPI_1_1OpenGLRendererAPI.html", null ]
    ] ],
    [ "Kargono::RendererInputSpec", "structKargono_1_1RendererInputSpec.html", null ],
    [ "Kargono::Rigidbody2DComponent", "structKargono_1_1Rigidbody2DComponent.html", null ],
    [ "Kargono::RuntimeUI::Runtime", "classKargono_1_1RuntimeUI_1_1Runtime.html", null ],
    [ "Kargono::Scene", "classKargono_1_1Scene.html", null ],
    [ "Kargono::SceneHierarchyPanel", "classKargono_1_1SceneHierarchyPanel.html", null ],
    [ "Kargono::Assets::SceneMetaData", "structKargono_1_1Assets_1_1SceneMetaData.html", null ],
    [ "Kargono::ScopedBuffer", "structKargono_1_1ScopedBuffer.html", null ],
    [ "Kargono::Timers::ScopedTimer", "classKargono_1_1Timers_1_1ScopedTimer.html", null ],
    [ "Kargono::Scripting::Script", "classKargono_1_1Scripting_1_1Script.html", null ],
    [ "Kargono::Script::ScriptClass", "classKargono_1_1Script_1_1ScriptClass.html", null ],
    [ "Kargono::Script::ScriptClassCustomCallInstance", "classKargono_1_1Script_1_1ScriptClassCustomCallInstance.html", null ],
    [ "Kargono::Script::ScriptClassEntityInstance", "classKargono_1_1Script_1_1ScriptClassEntityInstance.html", null ],
    [ "Kargono::ScriptComponent", "structKargono_1_1ScriptComponent.html", null ],
    [ "Kargono::Scripting::ScriptCore", "classKargono_1_1Scripting_1_1ScriptCore.html", null ],
    [ "Kargono::ScriptEditorPanel", "classKargono_1_1ScriptEditorPanel.html", null ],
    [ "Kargono::Script::ScriptEngine", "classKargono_1_1Script_1_1ScriptEngine.html", null ],
    [ "Kargono::Script::ScriptField", "structKargono_1_1Script_1_1ScriptField.html", null ],
    [ "Kargono::Script::ScriptFieldInstance", "structKargono_1_1Script_1_1ScriptFieldInstance.html", null ],
    [ "Kargono::Script::ScriptGlue", "classKargono_1_1Script_1_1ScriptGlue.html", null ],
    [ "Kargono::Assets::ScriptMetaData", "structKargono_1_1Assets_1_1ScriptMetaData.html", null ],
    [ "Kargono::Script::ScriptMethod", "structKargono_1_1Script_1_1ScriptMethod.html", null ],
    [ "Kargono::Scripting::ScriptModuleBuilder", "classKargono_1_1Scripting_1_1ScriptModuleBuilder.html", null ],
    [ "Kargono::Assets::AssetManager::ScriptSpec", "structKargono_1_1Assets_1_1AssetManager_1_1ScriptSpec.html", null ],
    [ "Kargono::EditorUI::SelectOptionSpec", "structKargono_1_1EditorUI_1_1SelectOptionSpec.html", null ],
    [ "Kargono::EditorUI::SelectorHeaderSpec", "structKargono_1_1EditorUI_1_1SelectorHeaderSpec.html", null ],
    [ "Kargono::Network::ServerInterface", "classKargono_1_1Network_1_1ServerInterface.html", [
      [ "Kargono::Network::Server", "classKargono_1_1Network_1_1Server.html", null ]
    ] ],
    [ "Kargono::Network::Session", "classKargono_1_1Network_1_1Session.html", null ],
    [ "Kargono::Network::SessionInitCache", "structKargono_1_1Network_1_1SessionInitCache.html", null ],
    [ "Kargono::Shader", "classKargono_1_1Shader.html", [
      [ "API::RenderingAPI::OpenGLShader", "classAPI_1_1RenderingAPI_1_1OpenGLShader.html", null ]
    ] ],
    [ "Kargono::ShaderBuilder", "classKargono_1_1ShaderBuilder.html", null ],
    [ "Kargono::Assets::ShaderMetaData", "structKargono_1_1Assets_1_1ShaderMetaData.html", null ],
    [ "Kargono::ShaderSpecification", "structKargono_1_1ShaderSpecification.html", null ],
    [ "Kargono::Shape", "classKargono_1_1Shape.html", null ],
    [ "Kargono::ShapeComponent", "structKargono_1_1ShapeComponent.html", null ],
    [ "Kargono::Renderer::Statistics", "structKargono_1_1Renderer_1_1Statistics.html", null ],
    [ "Kargono::StatisticsPanel", "classKargono_1_1StatisticsPanel.html", null ],
    [ "Kargono::EditorUI::TableEntry", "structKargono_1_1EditorUI_1_1TableEntry.html", null ],
    [ "Kargono::EditorUI::TableSpec", "structKargono_1_1EditorUI_1_1TableSpec.html", null ],
    [ "Kargono::TagComponent", "structKargono_1_1TagComponent.html", null ],
    [ "Kargono::RuntimeUI::Text", "classKargono_1_1RuntimeUI_1_1Text.html", null ],
    [ "Kargono::TextEditorPanel", "classKargono_1_1TextEditorPanel.html", null ],
    [ "Kargono::EditorUI::TextInputSpec", "structKargono_1_1EditorUI_1_1TextInputSpec.html", null ],
    [ "Kargono::Texture", "classKargono_1_1Texture.html", [
      [ "Kargono::Texture2D", "classKargono_1_1Texture2D.html", [
        [ "API::RenderingAPI::OpenGLTexture2D", "classAPI_1_1RenderingAPI_1_1OpenGLTexture2D.html", null ]
      ] ]
    ] ],
    [ "Kargono::Assets::TextureMetaData", "structKargono_1_1Assets_1_1TextureMetaData.html", null ],
    [ "Kargono::TextureSpecification", "structKargono_1_1TextureSpecification.html", null ],
    [ "Kargono::Utility::Time", "classKargono_1_1Utility_1_1Time.html", null ],
    [ "Kargono::Timestep", "classKargono_1_1Timestep.html", null ],
    [ "Kargono::TransformComponent", "structKargono_1_1TransformComponent.html", null ],
    [ "Kargono::Network::tsqueue< T >", "classKargono_1_1Network_1_1tsqueue.html", null ],
    [ "Kargono::Network::tsqueue< Kargono::Network::LabeledMessage >", "classKargono_1_1Network_1_1tsqueue.html", null ],
    [ "Kargono::Network::tsqueue< Kargono::Network::Message >", "classKargono_1_1Network_1_1tsqueue.html", null ],
    [ "Kargono::Network::tsqueue< Kargono::Network::owned_message >", "classKargono_1_1Network_1_1tsqueue.html", null ],
    [ "Kargono::Network::UDPService", "classKargono_1_1Network_1_1UDPService.html", [
      [ "Kargono::Network::UDPClient", "classKargono_1_1Network_1_1UDPClient.html", null ],
      [ "Kargono::Network::UDPServer", "classKargono_1_1Network_1_1UDPServer.html", null ]
    ] ],
    [ "Kargono::RuntimeUI::UICallbacks", "structKargono_1_1RuntimeUI_1_1UICallbacks.html", null ],
    [ "Kargono::UIEditorPanel", "classKargono_1_1UIEditorPanel.html", null ],
    [ "Kargono::RuntimeUI::UIObject", "structKargono_1_1RuntimeUI_1_1UIObject.html", null ],
    [ "Kargono::Assets::UIObjectMetaData", "structKargono_1_1Assets_1_1UIObjectMetaData.html", null ],
    [ "Kargono::UniformBuffer", "classKargono_1_1UniformBuffer.html", [
      [ "API::RenderingAPI::OpenGLUniformBuffer", "classAPI_1_1RenderingAPI_1_1OpenGLUniformBuffer.html", null ]
    ] ],
    [ "Kargono::UniformBufferList", "classKargono_1_1UniformBufferList.html", null ],
    [ "Kargono::UniformElement", "structKargono_1_1UniformElement.html", null ],
    [ "Kargono::UUID", "classKargono_1_1UUID.html", null ],
    [ "Kargono::VertexArray", "classKargono_1_1VertexArray.html", [
      [ "API::RenderingAPI::OpenGLVertexArray", "classAPI_1_1RenderingAPI_1_1OpenGLVertexArray.html", null ]
    ] ],
    [ "Kargono::VertexBuffer", "classKargono_1_1VertexBuffer.html", [
      [ "API::RenderingAPI::OpenGLVertexBuffer", "classAPI_1_1RenderingAPI_1_1OpenGLVertexBuffer.html", null ]
    ] ],
    [ "Kargono::ViewportPanel", "classKargono_1_1ViewportPanel.html", null ],
    [ "Kargono::RuntimeUI::Widget", "classKargono_1_1RuntimeUI_1_1Widget.html", [
      [ "Kargono::RuntimeUI::ButtonWidget", "classKargono_1_1RuntimeUI_1_1ButtonWidget.html", null ],
      [ "Kargono::RuntimeUI::CheckboxWidget", "classKargono_1_1RuntimeUI_1_1CheckboxWidget.html", null ],
      [ "Kargono::RuntimeUI::ComboWidget", "classKargono_1_1RuntimeUI_1_1ComboWidget.html", null ],
      [ "Kargono::RuntimeUI::PopupWidget", "classKargono_1_1RuntimeUI_1_1PopupWidget.html", null ],
      [ "Kargono::RuntimeUI::TextWidget", "classKargono_1_1RuntimeUI_1_1TextWidget.html", null ]
    ] ],
    [ "Kargono::RuntimeUI::WidgetCallbacks", "structKargono_1_1RuntimeUI_1_1WidgetCallbacks.html", null ],
    [ "Kargono::RuntimeUI::Window::WidgetCounts", "structKargono_1_1RuntimeUI_1_1Window_1_1WidgetCounts.html", null ],
    [ "Kargono::RuntimeUI::Window", "structKargono_1_1RuntimeUI_1_1Window.html", null ],
    [ "Kargono::Window", "classKargono_1_1Window.html", [
      [ "API::Platform::WindowsWindow", "classAPI_1_1Platform_1_1WindowsWindow.html", null ]
    ] ],
    [ "Kargono::WindowProps", "structKargono_1_1WindowProps.html", null ],
    [ "Kargono::WrappedFunction", "classKargono_1_1WrappedFunction.html", [
      [ "Kargono::WrappedBoolNone", "classKargono_1_1WrappedBoolNone.html", null ],
      [ "Kargono::WrappedBoolUInt64", "classKargono_1_1WrappedBoolUInt64.html", null ],
      [ "Kargono::WrappedBoolUInt64UInt16UInt64", "classKargono_1_1WrappedBoolUInt64UInt16UInt64.html", null ],
      [ "Kargono::WrappedBoolUInt64UInt64", "classKargono_1_1WrappedBoolUInt64UInt64.html", null ],
      [ "Kargono::WrappedVoidFloat", "classKargono_1_1WrappedVoidFloat.html", null ],
      [ "Kargono::WrappedVoidNone", "classKargono_1_1WrappedVoidNone.html", null ],
      [ "Kargono::WrappedVoidString", "classKargono_1_1WrappedVoidString.html", null ],
      [ "Kargono::WrappedVoidUInt16", "classKargono_1_1WrappedVoidUInt16.html", null ],
      [ "Kargono::WrappedVoidUInt32", "classKargono_1_1WrappedVoidUInt32.html", null ],
      [ "Kargono::WrappedVoidUInt64", "classKargono_1_1WrappedVoidUInt64.html", null ],
      [ "Kargono::WrappedVoidUInt64Float", "classKargono_1_1WrappedVoidUInt64Float.html", null ]
    ] ],
    [ "Kargono::WrappedVariable", "classKargono_1_1WrappedVariable.html", [
      [ "Kargono::WrappedBool", "classKargono_1_1WrappedBool.html", null ],
      [ "Kargono::WrappedFloat", "classKargono_1_1WrappedFloat.html", null ],
      [ "Kargono::WrappedInteger32", "classKargono_1_1WrappedInteger32.html", null ],
      [ "Kargono::WrappedString", "classKargono_1_1WrappedString.html", null ],
      [ "Kargono::WrappedUInteger16", "classKargono_1_1WrappedUInteger16.html", null ],
      [ "Kargono::WrappedUInteger32", "classKargono_1_1WrappedUInteger32.html", null ],
      [ "Kargono::WrappedUInteger64", "classKargono_1_1WrappedUInteger64.html", null ],
      [ "Kargono::WrappedVector3", "classKargono_1_1WrappedVector3.html", null ]
    ] ]
];