#pragma once
#define GLM_FORCE_SILENT_WARNINGS
#include <glm/glm.hpp>
#define GLM_ENABLE_EXPERIMENTAL
#include <glm/gtx/quaternion.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <glm/gtc/matrix_transform.hpp>
#undef GLM_ENABLE_EXPERIMENTAL
#undef GLM_FORCE_SILENT_WARNINGS
